"""Rendering CLIProxyAPI's YAML from the panel's state.

The providers come from the credentials store and the rest from
``config/cliproxyapi``; CLIProxyAPI never gets configured by hand. A provider's
kind decides which upstream block it lands in: ``anthropic`` speaks the
Messages protocol, ``openai`` the Responses protocol, ``gemini`` Google's,
and ``custom`` is an OpenAI-compatible chat endpoint.

Pure: state in, text out.
"""

import re

import yaml

from neutrino_hub.modules.cliproxyapi.config import CliproxyApiConfig
from neutrino_hub.modules.cliproxyapi.constants import CLIPROXYAPI_AUTH_DIR
from neutrino_hub.modules.credentials.registry import AiProviderRecord

KIND_TO_BLOCK = {
    "anthropic": "claude-api-key",
    "openai": "codex-api-key",
    "gemini": "gemini-api-key",
}


class CliproxyApiConfigRenderer:
    """Builds ``cliproxyapi.yaml`` from the parsed configuration."""

    def __init__(self, *, config: CliproxyApiConfig, providers: list[AiProviderRecord]):
        """
        Args:
            config: The gateway's own settings.
            providers: Every stored provider; disabled ones are left out.
        """
        self._config = config
        self._providers = providers

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready to write as ``cliproxyapi.yaml``.
        """
        document = {
            "host": "",
            "port": self._config.listen_port,
            "auth-dir": str(CLIPROXYAPI_AUTH_DIR),
            "api-keys": [key.key for key in self._config.client_keys],
            "logging-to-file": False,
        }
        compatibility = []
        for provider in self._providers:
            if not provider.is_enabled or not provider.api_key:
                continue
            if provider.kind in KIND_TO_BLOCK:
                entry = {"api-key": provider.api_key}
                if provider.base_url:
                    entry["base-url"] = provider.base_url
                models = self._models(provider)
                if models:
                    entry["models"] = models
                document.setdefault(KIND_TO_BLOCK[provider.kind], []).append(entry)
            else:
                entry = {
                    "name": _slug(provider.name),
                    "base-url": provider.base_url,
                    "api-key-entries": [{"api-key": provider.api_key}],
                }
                models = self._models(provider)
                if models:
                    entry["models"] = models
                compatibility.append(entry)
        if compatibility:
            document["openai-compatibility"] = compatibility
        rendered = yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
        return (
            "# Generated by neutrino. Do not edit; "
            "change the panel instead.\n" + rendered
        )

    def _models(self, provider: AiProviderRecord) -> list[dict]:
        models = []
        for entry in provider.models:
            name = str(entry.get("name", "")).strip()
            if not name:
                continue
            alias = str(entry.get("alias", "")).strip() or name
            models.append({"name": name, "alias": alias})
        return models


def _slug(name: str) -> str:
    slug = re.sub(r"[^a-z0-9_-]+", "-", name.lower()).strip("-")
    return slug or "provider"
