"""The TUN plan each scope renders on macOS and Windows, as the tests hold it.

One entry per system, scope and whether overlays run: the device, the
tun2socks start line, the routes in the order they are added, and the
interfaces forwarding is turned on for.
"""

UPPER_HALF = "128.0.0.0/1"  # scan: allow
TUN_ADDRESS = "198.18.0.1"  # scan: allow

PLANS = {
    "plan_darwin_hub_no_overlays": {
        "device": "utun225",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "/app/bin/tun2socks",
            "--device",
            "tun://utun225",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "en0",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "198.51.100.4/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": [],
    },
    "plan_darwin_hub_with_overlays": {
        "device": "utun225",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "/app/bin/tun2socks",
            "--device",
            "tun://utun225",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "en0",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "192.0.2.61/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.4/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.11/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.12/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.13/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": [],
    },
    "plan_darwin_overlay_with_overlays": {
        "device": "utun225",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "/app/bin/tun2socks",
            "--device",
            "tun://utun225",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "en0",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "192.0.2.61/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.4/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.11/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.12/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.13/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": ["utun4", "utun6"],
    },
    "plan_darwin_both_with_overlays": {
        "device": "utun225",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "/app/bin/tun2socks",
            "--device",
            "tun://utun225",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "en0",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "192.0.2.61/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.4/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.11/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.12/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.13/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "en0",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "utun225",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": ["utun4", "utun6"],
    },
    "plan_windows_hub_no_overlays": {
        "device": "neutrino_tun",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "C:\\hub\\bin\\tun2socks.exe",
            "--device",
            "tun://neutrino_tun",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "Ethernet",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "198.51.100.4/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": [],
    },
    "plan_windows_hub_with_overlays": {
        "device": "neutrino_tun",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "C:\\hub\\bin\\tun2socks.exe",
            "--device",
            "tun://neutrino_tun",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "Ethernet",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "192.0.2.61/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.4/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.11/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.12/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.13/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": [],
    },
    "plan_windows_overlay_with_overlays": {
        "device": "neutrino_tun",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "C:\\hub\\bin\\tun2socks.exe",
            "--device",
            "tun://neutrino_tun",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "Ethernet",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "192.0.2.61/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.4/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.11/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.12/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.13/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": ["wt0", "easytier", "neutrino_tun"],
    },
    "plan_windows_both_with_overlays": {
        "device": "neutrino_tun",
        "address": TUN_ADDRESS,
        "prefix_length": 30,
        "mtu": 1500,
        "start_argv": [
            "C:\\hub\\bin\\tun2socks.exe",
            "--device",
            "tun://neutrino_tun",
            "--proxy",
            "socks5://127.0.0.1:10087",
            "--mtu",
            "1500",
            "--loglevel",
            "warn",
        ],
        "uplink": "Ethernet",
        "gateway": "192.168.1.1",
        "routes": [
            {
                "destination": "192.0.2.61/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.4/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.11/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.12/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "198.51.100.13/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.10/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "203.0.113.11/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "223.5.5.5/32",
                "device": "Ethernet",
                "gateway": "192.168.1.1",
                "is_scoped": False,
            },
            {
                "destination": "0.0.0.0/1",
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
            {
                "destination": UPPER_HALF,
                "device": "neutrino_tun",
                "gateway": "",
                "is_scoped": False,
            },
        ],
        "forwarding_devices": ["wt0", "easytier", "neutrino_tun"],
    },
}
