"""Rendering the whole of ``app.ini`` from the git server's configuration.

The whole file, with ``INSTALL_LOCK`` already set: Gitea's browser install
wizard asks questions the hub already knows the answers to.

Pure: text in, text out.
"""

# PEP 604 unions below are annotations only; this keeps them lazy so the
# agent still imports on the Python 3.9 that older Raspbian ships.
from __future__ import annotations

from dataclasses import dataclass

from neutrino_agent.modules.gitea.config import GiteaConfig
from neutrino_agent.modules.gitea.constants import GITEA_DIR, GITEA_USER


@dataclass
class GiteaLayout:
    """Where one system's server runs, as ``app.ini`` names it.

    Attributes:
        run_user: The account the server runs as.
        work_path: Its data directory, with ``/`` between the parts on every
            system.
        git_path: The git it runs; empty leaves git to ``PATH``.
        is_ssh_served: Whether clone addresses offer SSH through the
            system's own ``sshd``.
        windows_service_name: The Windows service it runs as; empty
            elsewhere.
    """

    run_user: str = GITEA_USER
    work_path: str = GITEA_DIR
    git_path: str = ""
    is_ssh_served: bool = True
    windows_service_name: str = ""


class GiteaConfigRenderer:
    """Builds ``app.ini`` from the parsed configuration."""

    def __init__(self, *, config: GiteaConfig, layout: "GiteaLayout | None" = None):
        """
        Args:
            config: The parsed configuration, secrets included.
            layout: Where the server runs; None is the Linux one.
        """
        self._config = config
        self._layout = layout if layout is not None else GiteaLayout()

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready to write as ``app.ini``.
        """
        config = self._config
        root_url = config.derived_root_url
        # What clone addresses and links say, which need not be where it
        # binds.
        domain = root_url.split("//", 1)[1].split("/", 1)[0].split(":", 1)[0]
        registration = "false" if config.is_registration_enabled else "true"
        secrets = config.secrets
        layout = self._layout
        work = layout.work_path
        ssh_disabled = "false" if layout.is_ssh_served else "true"
        extra = ""
        if layout.git_path:
            extra += f"\n[git]\nPATH = {layout.git_path}\n"
        if layout.windows_service_name:
            extra += f"\n[windows]\nSERVICE_NAME = {layout.windows_service_name}\n"
        return f"""; Generated by neutrino. Do not edit; change it on the hub instead.

APP_NAME = Neutrino Gitea
RUN_USER = {layout.run_user}
RUN_MODE = prod
WORK_PATH = {work}

[server]
PROTOCOL = http
HTTP_ADDR = 0.0.0.0
HTTP_PORT = {config.listen_port}
DOMAIN = {domain}
ROOT_URL = {root_url}
DISABLE_SSH = {ssh_disabled}
START_SSH_SERVER = false
SSH_DOMAIN = {domain}
SSH_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = {secrets.get("LFS_JWT_SECRET", "")}
OFFLINE_MODE = true

[database]
DB_TYPE = sqlite3
PATH = {work}/data/gitea.db

[repository]
ROOT = {work}/data/gitea_repositories

[security]
INSTALL_LOCK = true
SECRET_KEY = {secrets.get("SECRET_KEY", "")}
INTERNAL_TOKEN = {secrets.get("INTERNAL_TOKEN", "")}

[oauth2]
JWT_SECRET = {secrets.get("JWT_SECRET", "")}

[service]
DISABLE_REGISTRATION = {registration}
REQUIRE_SIGNIN_VIEW = false

[session]
PROVIDER = file

[log]
MODE = file
ROOT_PATH = {work}/log
LEVEL = Info

[actions]
ENABLED = false
{extra}"""
