"""Rendering the whole of ``app.ini`` from the git server's configuration.

The whole file, with ``INSTALL_LOCK`` already set: Gitea's browser install
wizard asks questions the hub already knows the answers to.

Pure: text in, text out.
"""

# PEP 604 unions below are annotations only; this keeps them lazy so the
# agent still imports on the Python 3.9 that older Raspbian ships.
from __future__ import annotations

from neutrino_agent.modules.gitea.config import GiteaConfig
from neutrino_agent.modules.gitea.constants import GITEA_DIR, GITEA_USER


class GiteaConfigRenderer:
    """Builds ``app.ini`` from the parsed configuration."""

    def __init__(self, *, config: GiteaConfig):
        """
        Args:
            config: The parsed configuration, secrets included.
        """
        self._config = config

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready to write as ``app.ini``.
        """
        config = self._config
        root_url = config.derived_root_url
        # What clone addresses and links say, which need not be where it
        # binds.
        domain = root_url.split("//", 1)[1].split("/", 1)[0].split(":", 1)[0]
        registration = "false" if config.is_registration_enabled else "true"
        secrets = config.secrets
        return f"""; Generated by neutrino. Do not edit; change it on the hub instead.

APP_NAME = Neutrino Gitea
RUN_USER = {GITEA_USER}
RUN_MODE = prod
WORK_PATH = {GITEA_DIR}

[server]
PROTOCOL = http
HTTP_ADDR = 0.0.0.0
HTTP_PORT = {config.listen_port}
DOMAIN = {domain}
ROOT_URL = {root_url}
DISABLE_SSH = false
START_SSH_SERVER = false
SSH_DOMAIN = {domain}
SSH_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = {secrets.get("LFS_JWT_SECRET", "")}
OFFLINE_MODE = true

[database]
DB_TYPE = sqlite3
PATH = {GITEA_DIR}/data/gitea.db

[repository]
ROOT = {GITEA_DIR}/data/gitea_repositories

[security]
INSTALL_LOCK = true
SECRET_KEY = {secrets.get("SECRET_KEY", "")}
INTERNAL_TOKEN = {secrets.get("INTERNAL_TOKEN", "")}

[oauth2]
JWT_SECRET = {secrets.get("JWT_SECRET", "")}

[service]
DISABLE_REGISTRATION = {registration}
REQUIRE_SIGNIN_VIEW = false

[session]
PROVIDER = file

[log]
MODE = file
ROOT_PATH = {GITEA_DIR}/log
LEVEL = Info

[actions]
ENABLED = false
"""
