"""Build the hub's Arch package.

    python3 hub/packaging/build_pkg.py --output-dir dist/

The package carries the same environment the .deb and the .rpm do, described
as a PKGBUILD.

Needs `makepkg`, which refuses to run as root; this runs it as the invoking
user or as the one named by --build-user.

Not pure: creates a virtual environment, installs into it, runs makepkg.
"""

import argparse
import os
import pwd
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from venv_tree import (
    PACKAGE_NAME,
    dependencies,
    recommendations,
    PYTHON_DIR,
    build_environment,
    panel_unit,
    require_built_frontend,
    version,
    write,
    WRAPPER,
)

UNIT_DIR = "usr/lib/systemd/system"
# makepkg wants a reason beside every optional dependency.
ARCH_OPTIONAL_REASONS = {"hostapd": "serves a Wi-Fi access point"}

PKGBUILD = """# Generated by neutrino's packaging build. Do not edit.
pkgname={name}
pkgver={version}
pkgrel=1
pkgdesc="Neutrino Hub, a personal developer infrastructure hub"
arch=('{architecture}')
url="https://github.com/iffiX/neutrino"
license=('MIT' 'MPL-2.0' 'CC-BY-SA-4.0')
depends=({depends})
optdepends=({optdepends})
options=('!strip' '!debug' 'emptydirs')
# Without this makepkg writes no .INSTALL into the package and the hooks below
# never run, which shows up as a hub with nowhere to put its configuration.
install={name}.install

package() {{
    cp -a "{payload}/." "$pkgdir/"
}}
"""

INSTALL_SCRIPT = """pre_upgrade() {
    # Python writes __pycache__ into the carried tree while the hub runs;
    # pacman does not own those files, and a directory the new version no
    # longer ships would stay behind over them. Cleared before the new
    # files land.
    if [ -d /opt/neutrino ]; then
        find /opt/neutrino -type d -name __pycache__ -prune -print0 |
            xargs -0 -r rm -rf 2>/dev/null || true
    fi
}

post_install() {
    install -d -m 755 /etc/neutrino
    install -d -m 700 /etc/neutrino/hub
    install -d -m 755 /var/lib/neutrino
    install -d -m 755 /var/lib/neutrino/generated
    install -d -m 755 /var/log/neutrino
    echo ""
    echo "  Neutrino Hub installed. Set it up with:"
    echo ""
    echo "      sudo nhub setup"
    echo ""
}

post_upgrade() {
    # An upgrade can change the unit files and the software they start, and
    # `nhub apply` is what writes them onto a box somebody already set up.
    install -d -m 755 /etc/neutrino
    install -d -m 700 /etc/neutrino/hub
    install -d -m 755 /var/lib/neutrino
    install -d -m 755 /var/lib/neutrino/generated
    install -d -m 755 /var/log/neutrino
    nhub apply >/dev/null 2>&1 ||
        echo "  Run 'sudo nhub apply' to pick up this version."
    # And the panel, because it is the process running the code this package
    # just replaced. `nhub apply` re-renders what the modules produce and
    # restarts what consumes it, but the panel serves itself: without this it
    # goes on running the old Python behind the new frontend, which is a strip
    # asking for fields the old API does not send. Only when it is already up
    # — a box nobody has set up has no panel to restart.
    systemctl try-restart neutrino_hub_web.service >/dev/null 2>&1 || true
}

pre_remove() {
    for unit in neutrino_hub_web neutrino_hub_router neutrino_hub_xray neutrino_hub_cliproxyapi neutrino_hub_netbird neutrino_hub_easytier; do
        systemctl stop "${unit}.service" >/dev/null 2>&1 || true
        systemctl disable "${unit}.service" >/dev/null 2>&1 || true
    done
}

post_remove() {
    # What is left once pacman removes its own files is the bytecode the
    # interpreter wrote while it ran.
    rm -rf /opt/neutrino
    echo "  Leaving /etc/neutrino/hub in place; remove it by hand if you"
    echo "  no longer need the node credentials and device keys it holds."
}
"""


def main() -> int:
    """Build the package.

    Returns:
        The process exit status.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output-dir", default="dist", help="where to write the package"
    )
    parser.add_argument(
        "--architecture", default="x86_64", help="the arch field of the PKGBUILD"
    )
    parser.add_argument(
        "--build-user",
        default="",
        help="who runs makepkg, which refuses to run as root",
    )
    arguments = parser.parse_args()

    require_built_frontend()
    package_version = version()
    output_dir = Path(arguments.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    builder = arguments.build_user or _unprivileged_user()

    with tempfile.TemporaryDirectory() as workdir:
        root = Path(workdir)
        payload = root / "payload"
        build_environment(payload, package_version, arguments.architecture)
        write(
            payload / "usr/bin/nhub",
            WRAPPER.format(python=PYTHON_DIR),
            is_executable=True,
        )
        write(payload / UNIT_DIR / "neutrino_hub_web.service", panel_unit())

        write(root / f"{PACKAGE_NAME}.install", INSTALL_SCRIPT)
        write(
            root / "PKGBUILD",
            PKGBUILD.format(
                name=PACKAGE_NAME,
                version=package_version,
                architecture=arguments.architecture,
                payload=payload,
                depends=" ".join(f"'{name}'" for name in dependencies("arch")),
                optdepends=" ".join(
                    f"'{name}: {ARCH_OPTIONAL_REASONS[name]}'"
                    for name in recommendations("arch")
                ),
            ),
        )
        target = _build(root, output_dir, builder)

    print(f"wrote {target} ({target.stat().st_size // 1024 // 1024} MiB)")
    return 0


def _build(root: Path, output_dir: Path, builder: str) -> Path:
    """Run makepkg and move the result where it was asked for.

    Args:
        root: The directory holding the PKGBUILD.
        output_dir: Where the package should land.
        builder: The account makepkg runs as.

    Returns:
        The path written.

    Raises:
        SystemExit: If makepkg refuses, or writes nothing.
    """
    command = ["makepkg", "--nodeps", "--noconfirm", "--clean"]
    if os.geteuid() == 0:
        # makepkg will not run as root, and stepping down is `runuser`: sudo
        # is not on every Arch install and is not what this needs.
        shutil.chown(root, user=builder)
        command = ["runuser", "-u", builder, "--", *command]

    result = subprocess.run(command, cwd=root, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit((result.stderr or result.stdout).strip()[-2000:])

    built = sorted(root.glob(f"{PACKAGE_NAME}-*.pkg.tar.*"))
    if not built:
        raise SystemExit("makepkg wrote no package")
    target = output_dir / built[0].name
    shutil.copyfile(built[0], target)
    return target


def _unprivileged_user() -> str:
    """An account makepkg can run as.

    Returns:
        The invoking user when that is not root, otherwise ``nobody``.

    Raises:
        SystemExit: If run as root with no account named.
    """
    if os.geteuid() != 0:
        return pwd.getpwuid(os.geteuid()).pw_name
    raise SystemExit("makepkg will not run as root; name an account with --build-user")


if __name__ == "__main__":
    raise SystemExit(main())
