"""Unit names, package lists, and paths the deployment depends on."""

from pathlib import Path

# Units the panel shows and controls. The key is what the panel displays; the
# value is the systemd unit behind it.
# The units without which this is not a gateway. Traffic does not move if any
# of them is down, so the panel shows their state and their logs but offers no
# way to stop them: a gateway with dnsmasq disabled is not a gateway with a
# feature turned off, it is a broken gateway.
SYSTEM_CORE_UNITS = {
    "xray": "xray.service",
    "router": "neutrino_router.service",
    "dnsmasq": "dnsmasq.service",
    "web": "neutrino_web.service",
    # The way back into the box from anywhere else. Stopping it from abroad
    # is how the owner locks themselves out, so it gets the same no-off-switch
    # treatment as routing itself — installable, never stoppable or removable.
    "netbird": "netbird.service",
    # The AI gateway: every machine's tools point at it, so taking it down
    # takes their AI away — same no-off-switch treatment as netbird.
    "cliproxy": "neutrino_cliproxy.service",
}

# What the box also happens to host because it is already there and always on.
# Each is off until asked for, and enabling one is what makes its page appear
# in the sidebar — so the panel stays as small as the appliance actually is.
SYSTEM_OPTIONAL_UNITS = {
    "samba": "smbd.service",
    "gitea": "gitea.service",
    # Podman has no daemon; its API socket stands for the engine here.
    "podman": "podman.socket",
    # The event daemon stands for ZFS: pools work without it, but it is the
    # monitorable part, and its presence is what puts the page in the sidebar.
    "zfs": "zfs-zed.service",
}

SYSTEM_MANAGED_UNITS = {**SYSTEM_CORE_UNITS, **SYSTEM_OPTIONAL_UNITS}

# Installed from the distribution. Optional modules are not here — each
# installs through its own provisioner, from the panel or the installer's
# extras — and everything vendored (xray, netbird, gitea) comes from its
# vendor because the distribution versions lag badly.
#
# Every name below is spelled the same on Debian, RHEL and Arch except the
# ones in SYSTEM_PACKAGE_NAMES.
# What a provisioner can ask agreement for. The panel words each of these;
# nothing here or below it writes a sentence, so they can be translated and
# these stay facts.
SYSTEM_CONSENT_KERNEL_MODULE_BUILD = "kernel_module_build"
SYSTEM_CONSENT_THIRD_PARTY_REPOSITORY = "third_party_repository"

SYSTEM_BASE_PACKAGES = (
    "nftables",
    "dnsmasq",
    "vnstat",
    "arp-scan",
    "git",
    "curl",
    "unzip",
    "ethtool",
    # Reports what a radio can actually do. The panel asks it whether a Wi-Fi
    # card supports access-point mode before offering to serve a network on it.
    "iw",
    # Bans SSH brute-force sources at the firewall, on the same escalating
    # ladder the panel login uses. Configured by the installer's jail file.
    "fail2ban",
    # Runs the access point when a radio is given the LAN role. NetworkManager
    # will not do it on our terms: its AP mode forces shared addressing, which
    # starts a second dnsmasq that both holds port 53 and answers clients
    # outside the proxy.
    "hostapd",
    "python3-venv",
)

# Where a family spells a base package differently. A name absent from a
# family's entry keeps the name above; a name mapped to None is one that
# family has no separate package for, because it is already installed.
SYSTEM_PACKAGE_NAMES = {
    "debian": {},
    "rhel": {
        "dnsmasq": "dnsmasq",
        # RHEL builds venv into the interpreter rather than splitting it out.
        "python3-venv": None,
    },
    "arch": {
        "python3-venv": None,
    },
}

# The panel runs from a virtual environment inside the repo rather than from
# system packages: Ubuntu marks its Python externally managed, and an appliance
# should not have its dependencies changed out from under it by an apt upgrade.
SYSTEM_VENV_DIR_NAME = ".venv"

SYSTEM_XRAY_USER = "xray"

SYSTEM_SYSTEMD_DIR = Path("/etc/systemd/system")

# Where the installer writes fail2ban's policy, and the policy itself: five
# free failures, then bans that stretch from 30 seconds to a day — the same
# ladder as the panel login, but per source address, because one shared
# lockout would let anyone shut the owner out of their own box. The overlay
# range stays exempt: NetBird is the way back in and must never self-ban.
SYSTEM_FAIL2BAN_JAIL_PATH = Path("/etc/fail2ban/jail.d/neutrino.conf")
SYSTEM_FAIL2BAN_JAIL = """\
# Generated by neutrino. Do not edit; the installer owns it.
[sshd]
enabled = true
backend = systemd
maxretry = 5
findtime = 10m
banaction = nftables-multiport
banaction_allports = nftables-allports
bantime = 30
bantime.increment = true
bantime.multipliers = 1 2 10 120 2880
ignoreip = 127.0.0.1/8 ::1 100.88.0.0/16
"""
