"""Rendering declared containers into Quadlet unit files.

Quadlet is why podman fits this gateway: a ``.container`` file becomes an
ordinary systemd unit, so a declared container is supervised, journalled and
rebooted-with-the-box exactly like everything else here — no daemon, no
second init system.

Pure: config in, one file's text per container out. Writing them and telling
systemd is :mod:`neutrino_hub.modules.podman.ops`.
"""

from neutrino_hub.modules.podman.config import PodmanConfig, PodmanContainer


def qualified_image(image: str) -> str:
    """The fully-qualified form of an image reference.

    The page keeps the short form people actually write — ``python:3.12`` —
    but a unit file must not depend on short-name resolution, which varies by
    distro configuration and can stop a boot-time pull to ask a question.

    Args:
        image: A reference, short or already qualified.

    Returns:
        The reference with its registry spelled out.
    """
    first = image.split("/", 1)[0]
    if "/" in image and ("." in first or ":" in first):
        # Already names a registry (ghcr.io/..., localhost:5000/...).
        return image
    if "/" not in image:
        return f"docker.io/library/{image}"
    return f"docker.io/{image}"


# Every rendered file starts with this, which is how apply tells its own
# files from any a person drops beside them — those are never touched.
GENERATED_MARKER = "# Generated by neutrino. Do not edit; change config/ instead."


class PodmanQuadletRenderer:
    """Builds one Quadlet ``.container`` file per declared container."""

    def __init__(self, *, config: PodmanConfig):
        """
        Args:
            config: The parsed container declarations.
        """
        self._config = config

    def render(self) -> dict[str, str]:
        """Render every declared container.

        Returns:
            File contents keyed by file name, ``<name>.container``.
        """
        return {
            f"{container.name}.container": self._render_container(container)
            for container in self._config.containers
        }

    def render_registries(self) -> str:
        """Render the docker.io mirror drop-in.

        Returns:
            The registries.conf.d file, or an empty string when no mirrors are
            declared — the applier removes the drop-in then, and pulls go
            straight to the registry.
        """
        if not self._config.mirrors:
            return ""
        lines = [
            GENERATED_MARKER,
            "",
            "[[registry]]",
            'prefix = "docker.io"',
            'location = "registry-1.docker.io"',
        ]
        for mirror in self._config.mirrors:
            lines += [
                "",
                "[[registry.mirror]]",
                f'location = "{mirror}"',
            ]
        lines.append("")
        return "\n".join(lines)

    def _render_container(self, container: PodmanContainer) -> str:
        lines = [
            GENERATED_MARKER,
            "",
            "[Unit]",
            f"Description={container.name} container",
            "After=network-online.target",
            "",
            "[Container]",
            f"ContainerName={container.name}",
            f"Image={qualified_image(container.image)}",
        ]
        for port in container.ports:
            lines.append(f"PublishPort={port}")
        for volume in container.volumes:
            lines.append(f"Volume={volume}")
        for entry in container.environment:
            lines.append(f"Environment={entry}")
        if container.command:
            lines.append(f"Exec={container.command}")
        lines += [
            "",
            "[Service]",
            # Pulling a large image on first start takes longer than the
            # default start timeout wants to allow.
            "TimeoutStartSec=900",
            "Restart=on-failure",
        ]
        if container.is_autostart:
            lines += [
                "",
                "[Install]",
                "WantedBy=multi-user.target",
            ]
        lines.append("")
        return "\n".join(lines)
