"""Fixed values of the netbird module."""

from pathlib import Path

from neutrino_hub.utils.constants import UTILS_STATIC_ROOT

# What the hub's package carries. The packaging pins the same version in
# hub/packaging/venv_tree.py by reading this file, so a release and a checkout
# put the same client on a machine. The vendor's release assets name the
# machine the way this project does, so one table serves both.
NETBIRD_VERSION = "0.78.1"
NETBIRD_DOWNLOAD_URL = (
    "https://github.com/netbirdio/netbird/releases/download/"
    "v{version}/netbird_{version}_linux_{asset_arch}.tar.gz"
)
NETBIRD_ASSET_ARCHITECTURES = {"amd64": "amd64", "arm64": "arm64"}
NETBIRD_SHA256 = {
    "amd64": "9239c9e37c2acc0612563ef5ce0c3326397460d0eb811b5a59a8e373f1a4ebde",  # scan: allow
    "arm64": "d686745aa64bb4c597602ce95e76558f5f848d0672c88d63f96397d2507005b2",  # scan: allow
}
NETBIRD_SUPPORTED_ARCHITECTURES = ("amd64", "arm64")
NETBIRD_BINARY_NAME = "netbird"
# Under the hub's own prefix, beside xray and the AI gateway, because the
# package carries it rather than a vendor repository installing it.
NETBIRD_BINARY_PATH = UTILS_STATIC_ROOT / "bin" / NETBIRD_BINARY_NAME

# The unit the hub writes and drives. The vendor's own is generated by
# `netbird service install` under this name; the two daemons share a state
# file and a socket, so the one below is stood down before ours starts.
NETBIRD_UNIT = "neutrino_hub_netbird.service"
NETBIRD_VENDOR_UNIT = "netbird.service"

# Where the daemon keeps what it was last told, and how the current profile is
# named. Read rather than written: this is the vendor's file, and the only
# thing asked of it is what NetBird believes right now, so that setting it
# again when it already agrees does not cost a reconnection. The older
# single-file layout is still read, because a box that upgraded NetBird keeps
# it. Both are absent on a machine that never enrolled, which reads as
# "unknown" and is answered by setting it rather than assuming.
#
# These stay the vendor's paths although the binary is ours. `--config` moves
# the profile, but the state file beside it — the register of the firewall,
# DNS and route changes to revert — is fixed in the client and has no flag,
# so moving the profile alone would split one layout across two roots and
# still leave every NetBird on the machine sharing that register.
NETBIRD_STATE_DIR = Path("/var/lib/netbird")
NETBIRD_ACTIVE_PROFILE_PATH = NETBIRD_STATE_DIR / "active_profile.json"
NETBIRD_LEGACY_CONFIG_PATH = Path("/etc/netbird/config.json")
NETBIRD_BLOCK_INBOUND_KEY = "BlockInbound"

# `netbird up` re-establishes the session, so it is given the same room as an
# enrollment rather than a command's usual seconds.
NETBIRD_INBOUND_TIMEOUT_S = 60
