"""Fixed values of the netbird module."""

from pathlib import Path

from neutrino_hub.utils.constants import UTILS_STATE_ROOT, carried_program

# What the hub's package carries. The packaging pins the same version in
# hub/packaging/venv_tree.py by reading this file, so a release and a checkout
# put the same client on a machine. The vendor's release assets name the
# machine the way this project does, so one table serves both.
NETBIRD_VERSION = "0.78.1"
NETBIRD_DOWNLOAD_URL = (
    "https://github.com/netbirdio/netbird/releases/download/"
    "v{version}/netbird_{version}_linux_{asset_arch}.tar.gz"
)
NETBIRD_ASSET_ARCHITECTURES = {"amd64": "amd64", "arm64": "arm64"}
NETBIRD_SHA256 = {
    "amd64": "9239c9e37c2acc0612563ef5ce0c3326397460d0eb811b5a59a8e373f1a4ebde",  # scan: allow
    "arm64": "d686745aa64bb4c597602ce95e76558f5f848d0672c88d63f96397d2507005b2",  # scan: allow
}
NETBIRD_SUPPORTED_ARCHITECTURES = ("amd64", "arm64")
NETBIRD_BINARY_NAME = "netbird"
# The asset each system and machine takes from the same release, and its
# hash, for every system a hub package is built for. The Linux rows are the
# files the two tables above name.
NETBIRD_RELEASE_URL = (
    "https://github.com/netbirdio/netbird/releases/download/v{version}/{asset}"
)
NETBIRD_ASSETS = {
    ("linux", "amd64"): (
        "netbird_0.78.1_linux_amd64.tar.gz",
        NETBIRD_SHA256["amd64"],
    ),
    ("linux", "arm64"): (
        "netbird_0.78.1_linux_arm64.tar.gz",
        NETBIRD_SHA256["arm64"],
    ),
    ("darwin", "amd64"): (
        "netbird_0.78.1_darwin_amd64.tar.gz",
        "1441be19db0394497866fc19a519d7d0483fbad0fcd4d1adaeb0ed1bded739be",  # scan: allow
    ),
    ("darwin", "arm64"): (
        "netbird_0.78.1_darwin_arm64.tar.gz",
        "8d613dc78aa0e5b9f01b07ec9d02417c27638bf68b829a72399293f76da0fa03",  # scan: allow
    ),
    ("windows", "amd64"): (
        "netbird_0.78.1_windows_amd64.tar.gz",
        "c9ad0e7aa778b9ba28b3e2338354d705df7ead94cdf6edbde137bdae79d30eab",  # scan: allow
    ),
}
# Under the hub's own prefix, beside xray and the AI gateway, because the
# package carries it rather than a vendor repository installing it.
NETBIRD_BINARY_PATH = carried_program(NETBIRD_BINARY_NAME)

# The unit the hub writes and drives. The vendor's own is generated by
# `netbird service install` under this name; the two daemons share a state
# file and a socket, so the one below is stood down before ours starts.
NETBIRD_UNIT = "neutrino_hub_netbird.service"
NETBIRD_VENDOR_UNIT = "netbird.service"

# Where the daemon keeps what it was last told, and how the current profile is
# named. Read rather than written: this is the vendor's file, and the only
# thing asked of it is what NetBird believes right now, so that setting it
# again when it already agrees does not cost a reconnection. The older
# single-file layout is still read, because a box that upgraded NetBird keeps
# it. Both are absent on a machine that never enrolled, which reads as
# "unknown" and is answered by setting it rather than assuming.
#
# These stay the vendor's paths although the binary is ours. `--config` moves
# the profile, but the state file beside it — the register of the firewall,
# DNS and route changes to revert — is fixed in the client and has no flag,
# so moving the profile alone would split one layout across two roots and
# still leave every NetBird on the machine sharing that register.
NETBIRD_STATE_DIR = Path("/var/lib/netbird")
NETBIRD_ACTIVE_PROFILE_PATH = NETBIRD_STATE_DIR / "active_profile.json"
NETBIRD_LEGACY_CONFIG_PATH = Path("/etc/netbird/config.json")
# On macOS and Windows the hub's own daemon keeps them beside the hub's
# state, started with `--config` naming the single-file profile there.
NETBIRD_HUB_STATE_DIR = UTILS_STATE_ROOT / "netbird"
NETBIRD_HUB_CONFIG_NAME = "config.json"
NETBIRD_ACTIVE_PROFILE_NAME = "active_profile.json"
# The name the process controller knows the daemon by.
NETBIRD_SUPERVISED_NAME = "netbird"
# Where every `netbird` command names the daemon it talks to.
NETBIRD_DAEMON_ADDRESS_FLAG = "--daemon-addr"
NETBIRD_BLOCK_INBOUND_KEY = "BlockInbound"
# The daemon's DNS management stays off on the hub: the box resolves at its
# own dnsmasq, and an overlay's DNS is a member's tool for roaming through the
# hub as its exit, never the hub's. Stored in the profile like BlockInbound,
# and stated on every `netbird up`, since a flag left off keeps its stored
# value.
NETBIRD_DISABLE_DNS_KEY = "DisableDNS"
NETBIRD_DISABLE_DNS_FLAG = "--disable-dns"

# `netbird up` re-establishes the session, so it is given the same room as an
# enrollment rather than a command's usual seconds.
NETBIRD_INBOUND_TIMEOUT_S = 60
# The daemon's words for a profile that holds no login the plane takes: one
# that never enrolled, one the plane refused, and one whose SSO session ran
# out. A join with a setup key starts from a deregistered profile in each,
# since the daemon registers a new peer only from a profile without one.
NETBIRD_STATUSES_WITHOUT_LOGIN = ("NeedsLogin", "LoginFailed", "SessionExpired")
# `netbird deregister` asks the plane to delete the peer; it fails, and
# deletes nothing, when the plane does not answer. A restart of the daemon
# with no profile on disk writes a fresh one with a new key.
NETBIRD_DEREGISTER_TIMEOUT_S = 60
NETBIRD_RESTART_SETTLE_S = 10
# `netbird routes list` names each route's destination on one of these lines,
# the older word first.
NETBIRD_ROUTE_RANGE_KEYS = ("Network", "Range")
NETBIRD_ROUTES_TIMEOUT_S = 15
NETBIRD_STATE_FILE_NAME = "state.json"

# Where the panel keeps the setup key the box joined with, and the management
# plane it belongs to. The key is reusable and every client admitted to the
# overlay joins with it, so it is sealed under the vault's data key.
NETBIRD_CONFIG_NAME = "netbird/netbird.json"
NETBIRD_SETUP_KEY_AAD = b"netbird:setup_key"
