"""Fixed values of the container engine module."""

# From 4.4 a rendered .container file becomes a unit; below it that file is
# inert, so the applier writes plain .service units running `podman run`.
PODMAN_QUADLET_VERSION = "4.4"

# Podman has no daemon; the API socket stands for the engine.
PODMAN_UNIT = "podman.socket"

# Units name the binary in full: systemd runs them with a minimal PATH.
PODMAN_BINARY = "/usr/bin/podman"

# Where a unit rendered for a podman without Quadlet lands.
PODMAN_UNIT_DIR = "/etc/systemd/system"

# Where Quadlet reads declared containers from.
PODMAN_QUADLET_DIR = "/etc/containers/systemd"

# Where the docker.io mirror list lands. A drop-in, so the distribution's
# own registries.conf stays untouched.
PODMAN_REGISTRIES_CONF_PATH = (
    "/etc/containers/registries.conf.d/99_neutrino_mirrors.conf"
)

# Every rendered file starts with this, which is how apply tells its own
# files from any a person drops beside them.
PODMAN_GENERATED_MARKER = (
    "# Generated by neutrino. Do not edit; change it on the hub instead."
)

PODMAN_CONTAINER_ACTIONS = ("start", "stop", "restart")

PODMAN_COMMAND_CONTROL = "podman_control"
PODMAN_COMMAND_JOURNAL = "podman_journal"
PODMAN_JOURNAL_LINES = 200
