"""Rendering the `dhcpcd` configuration an uplink takes its lease with.

One file per uplink, because the one thing that differs between them is the
route metric, and that is what decides which uplink the box actually leaves by.

`dhcpcd` is driven the way dnsmasq already is: our configuration, our state
directory, and every hook the distribution ships turned off. Measured on
Debian 12 it ships `20-resolv.conf`, `30-hostname` and four time-sync hooks;
left on, it is not an engine that fetches a lease, it is a second manager with
opinions about the resolver, the hostname and the clock — and the resolver is
the hub's, pointing at its own dnsmasq.

Pure: this module turns configuration into text. Starting the client is
:mod:`neutrino_hub.modules.router.dhcp_client`.
"""

from neutrino_hub.modules.router.constants import ROUTER_DHCP_STATE_DIR

# What the hooks are called in the argument `nohook` takes. The numbers the
# files carry are not part of the name.
DHCP_DISABLED_HOOKS = (
    "resolv.conf",
    "hostname",
    "ntp.conf",
    "timesync",
    "chrony",
    "openresolv",
)


class RouterDhcpRenderer:
    """Builds one uplink's dhcpcd configuration."""

    def __init__(self, *, interface: str, route_metric: int):
        """
        Args:
            interface: The uplink this configuration is for.
            route_metric: What to install its default route at. This is how
                one uplink comes to be preferred over another, and it is the
                only thing that differs between two uplinks' files.
        """
        self._interface = interface
        self._route_metric = route_metric

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready for ``dhcpcd -f``.
        """
        lines = [
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
            # Everything the distribution would have run on every lease. The
            # resolver belongs to the hub's own dnsmasq, the hostname to
            # whoever set it, and the clock to whatever the machine already
            # runs for it.
            f"nohook {', '.join(DHCP_DISABLED_HOOKS)}",
            "",
            f"interface {self._interface}",
            # Where this uplink's route lands. The gateway's own balancing
            # route is installed below whatever the uplinks really carry, so
            # this being honest is what makes the ranking mean anything.
            f"    metric {self._route_metric}",
            # Identify this machine by its hardware address rather than by a
            # DUID of dhcpcd's own. Taking an interface over from another
            # manager means asking the same DHCP server as a client it has
            # already met, and a private identifier makes it a stranger: the
            # server hands out a second address, and whoever was connected
            # over the first one is dropped. An empty clientid is dhcpcd's
            # way of saying "the hardware address".
            "    clientid",
            # And ask for the address the interface already has. With no
            # argument this is exactly that, which is why the handover puts
            # the address back before starting the client.
            "    request",
            "    persistent",
            "    option rapid_commit",
            "    option classless_static_routes",
            "    option interface_mtu",
            # A server that will not identify itself is not one to take a
            # lease from.
            "    require dhcp_server_identifier",
            # No address invented when nobody answers. dhcpcd falls back to
            # IPv4LL and puts a 169.254 address on the interface with a
            # default route beside it — on a port with no DHCP server that is
            # a made-up address and a way out that leads nowhere, and it
            # outranks nothing while sitting in the routing table. An uplink
            # that got no lease has no address, which is the truth.
            "    noipv4ll",
            # IPv4 only, which is what the whole router layer is: the
            # nftables ruleset, the policy route and the proxy interception
            # are all IPv4, and a client that brought up IPv6 as well would be
            # configuring something nothing else here knows about.
            "    noipv6",
            "",
        ]
        return "\n".join(lines)

    @property
    def state_dir(self):
        """Where the lease database goes.

        Returns:
            The hub's own directory, so `/var/lib/dhcpcd` — which may hold the
            machine's own leases — is neither read nor written.
        """
        return ROUTER_DHCP_STATE_DIR
