"""Rendering the dnsmasq configuration that serves the LAN.

dnsmasq owns DHCP and DNS on the LAN interfaces only. Its upstreams are the
network's resolvers, unless the proxy takes the LAN's traffic: then the
proxy's part, from the edition table, names where queries go.
"""

from neutrino_hub import edition
from neutrino_hub.modules.router.constants import (
    ROUTER_DNS_CACHE_SIZE,
    ROUTER_DNS_MIN_CACHE_TTL_S,
    ROUTER_DNS_NEG_TTL_S,
    ROUTER_HUB_NAME,
)
from neutrino_hub.modules.router.interfaces import (
    RouterInterface,
    RouterNetworkConfig,
    RouterStaticLease,
)
from neutrino_hub.modules.router.network_resolvers import fallback_resolvers

# Named when the box serves no network at all. dnsmasq with no interface named
# listens on every one of them, which here would mean answering DNS on the
# uplink; pointing it at an interface that does not exist is how it is told to
# serve nothing while still starting cleanly. Only bind-dynamic tolerates a name
# that resolves to nothing, which is the other reason the renderer uses it.
NO_LAN_PLACEHOLDER_INTERFACE = "neutrino_none"


class RouterDnsmasqRenderer:
    """Builds the whole dnsmasq configuration from the router config."""

    def __init__(
        self,
        *,
        network: RouterNetworkConfig,
        routing: dict | None = None,
        network_resolvers: list[dict] | None = None,
    ):
        """
        Args:
            network: The parsed router configuration. Every interface with the
                LAN role gets served; the rest are not mentioned at all.
            routing: The proxy's routing options, which its part reads to
                decide where queries go; empty in a tree without the proxy.
            network_resolvers: The network's resolvers as ``{address, port}``,
                in the order they are asked; None is the built-in fallbacks.
        """
        self._lans = network.lan_interfaces
        self._static_leases = network.static_leases
        self._routing = routing or {}
        self._network_resolvers = (
            fallback_resolvers() if network_resolvers is None else network_resolvers
        )

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready to write where ``neutrino_hub_dnsmasq.service``
            names it. Whole rather than a fragment: no configuration
            directory is read, so nothing a distribution ships beside it
            takes part.
        """
        lines = self._render_listeners()
        lines += self._render_hub_name()
        lines += self._render_dhcp()
        lines += self._render_upstream()
        lines += [
            "domain-needed",
            "bogus-priv",
            f"cache-size={ROUTER_DNS_CACHE_SIZE}",
            f"min-cache-ttl={ROUTER_DNS_MIN_CACHE_TTL_S}",
            f"neg-ttl={ROUTER_DNS_NEG_TTL_S}",
            "",
            "# Query log feeds the panel's DNS tab. `-` is stderr, which the",
            "# unit hands to systemd, so the journal holds it under its own",
            "# size limits rather than a file of ours growing without one.",
            "log-queries",
            "log-facility=-",
            "log-async=25",
            "",
        ]
        return "\n".join(lines)

    def _render_listeners(self) -> list[str]:
        header = [
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
        ]
        if not self._lans:
            # bind-dynamic rather than bind-interfaces: it tolerates an
            # interface that is not there, which is the whole point here.
            return header + [
                "# No interface has the LAN role, so there is nothing to serve.",
                f"interface={NO_LAN_PLACEHOLDER_INTERFACE}",
                "bind-dynamic",
                "",
            ]
        lines = header + [
            "# Serve the gateway's own networks only, and nothing else — in",
            "# particular not loopback, where it would collide with the",
            "# systemd-resolved stub on 127.0.0.53, and not an uplink, where it",
            "# would answer the whole internet.",
            "#",
            "# bind-dynamic rather than bind-interfaces, for two reasons. It binds",
            "# each named interface once, where bind-interfaces plus a matching",
            "# listen-address asks for the same socket twice and dies on 'Address",
            "# already in use' as soon as there are two LANs. And it tolerates a",
            "# named interface that is not there yet: a Wi-Fi access point appears",
            "# only once the radio is up, and under bind-interfaces its absence",
            "# stops dnsmasq starting at all, taking DHCP and DNS off the wired LAN",
            "# too. One radio failing to come up must not darken the whole box.",
            "except-interface=lo",
            "bind-dynamic",
        ]
        for interface in self._lans:
            lines.append(f"interface={interface.device_name}")
        lines.append("")
        return lines

    def _render_hub_name(self) -> list[str]:
        """This box by name on every served network that has an address.

        ``interface-name`` answers with the interface's own address, and
        ``localise-queries`` picks, of the addresses that name has, the one
        on the network the query arrived from.
        """
        served = [interface for interface in self._lans if interface.lan.address]
        if not served:
            return []
        lines = [
            f"# {ROUTER_HUB_NAME} is this box, at its address on the network the",
            "# query came in on.",
            "localise-queries",
        ]
        for interface in served:
            lines.append(f"interface-name={ROUTER_HUB_NAME},{interface.device_name}")
        lines.append("")
        return lines

    def _render_upstream(self) -> list[str]:
        """Where queries go: the proxy's upstream while it takes the LAN.

        With the LAN not proxied, queries go straight to the network's
        resolvers, and the box works as a plain router with the proxy not
        running at all.
        """
        upstream = edition.hook("router_dnsmasq")
        if upstream is not None:
            lines = upstream(self._routing, self._network_resolvers)
            if lines is not None:
                return lines
        return [
            "# LAN traffic is not proxied, so queries go to the network's",
            "# resolvers.",
            "no-resolv",
            *_server_lines(self._network_resolvers),
            "",
        ]

    def _render_dhcp(self) -> list[str]:
        pools = [
            interface
            for interface in self._lans
            if interface.lan.is_dhcp_enabled and interface.lan.dhcp_range_start
        ]
        if not pools:
            return ["# No LAN hands out leases; dnsmasq serves DNS only.", ""]
        lines = [
            "# DHCP: clients get this box as both gateway and resolver. dnsmasq tags",
            "# every request with the interface it arrived on, which is what keeps a",
            "# client on one network from being handed the gateway's address on",
            "# another.",
        ]
        for interface in pools:
            lines += self._render_pool(interface)
        if self._static_leases:
            lines.append("# Fixed addresses, one per MAC. A name resolves in DNS too.")
            for lease in self._static_leases:
                lines.append(self._render_static_lease(lease))
        lines += ["dhcp-authoritative", ""]
        return lines

    def _render_pool(self, interface: RouterInterface) -> list[str]:
        lan = interface.lan
        device = interface.device_name
        return [
            f"dhcp-range={lan.dhcp_range_start},{lan.dhcp_range_end},"
            f"{lan.dhcp_lease_time}",
            f"dhcp-option=tag:{device},option:router,{lan.address}",
            f"dhcp-option=tag:{device},option:dns-server,{lan.address}",
        ]

    def _render_static_lease(self, lease: RouterStaticLease) -> str:
        fields = [lease.mac_address, lease.address]
        if lease.name:
            fields.append(lease.name)
        return "dhcp-host=" + ",".join(fields)


def _server_lines(resolvers: list[dict]) -> list[str]:
    """One ``server=`` line per resolver, in the order they are asked."""
    return [f"server={entry['address']}#{entry['port']}" for entry in resolvers]
