"""Rendering the dnsmasq configuration that serves the LAN.

dnsmasq owns DHCP and DNS on the LAN interfaces only. Its sole upstream is the
xray DNS inbound on loopback, so a LAN name is resolved at the exit node and no
plaintext query ever leaves a WAN interface.
"""

from neutrino_hub.utils.constants import UTILS_LOG_DIR
from neutrino_hub.modules.xray.constants import XRAY_DNS_LISTEN, XRAY_DNS_PORT

from neutrino_hub.modules.router.interfaces import RouterInterface, RouterNetworkConfig

# Named when the box serves no network at all. dnsmasq with no interface named
# listens on every one of them, which here would mean answering DNS on the
# uplink; pointing it at an interface that does not exist is how it is told to
# serve nothing while still starting cleanly. Only bind-dynamic tolerates a name
# that resolves to nothing, which is the other reason the renderer uses it.
NO_LAN_PLACEHOLDER_INTERFACE = "neutrino_none"


class RouterDnsmasqRenderer:
    """Builds ``/etc/dnsmasq.d/neutrino.conf`` from the router config."""

    def __init__(self, *, network: RouterNetworkConfig, routing: dict | None = None):
        """
        Args:
            network: The parsed router configuration. Every interface with the
                LAN role gets served; the rest are not mentioned at all.
            routing: Parsed ``config/xray/routing.json``. Only the master proxy
                switch and the direct resolver are read, to decide where
                queries go.
        """
        self._lans = network.lan_interfaces
        self._routing = routing or {}

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready to write into ``/etc/dnsmasq.d/``.
        """
        lines = self._render_listeners()
        lines += self._render_dhcp()
        lines += self._render_upstream()
        lines += [
            "domain-needed",
            "bogus-priv",
            "cache-size=1000",
            "",
            "# Query log feeds the panel's DNS tab.",
            "log-queries",
            f"log-facility={UTILS_LOG_DIR / 'dnsmasq.log'}",
            "log-async=25",
            "",
        ]
        return "\n".join(lines)

    def _render_listeners(self) -> list[str]:
        header = [
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
        ]
        if not self._lans:
            # bind-dynamic rather than bind-interfaces: it tolerates an
            # interface that is not there, which is the whole point here.
            return header + [
                "# No interface has the LAN role, so there is nothing to serve.",
                f"interface={NO_LAN_PLACEHOLDER_INTERFACE}",
                "bind-dynamic",
                "",
            ]
        lines = header + [
            "# Serve the gateway's own networks only, and nothing else — in",
            "# particular not loopback, where it would collide with the",
            "# systemd-resolved stub on 127.0.0.53, and not an uplink, where it",
            "# would answer the whole internet.",
            "#",
            "# bind-dynamic rather than bind-interfaces, for two reasons. It binds",
            "# each named interface once, where bind-interfaces plus a matching",
            "# listen-address asks for the same socket twice and dies on 'Address",
            "# already in use' as soon as there are two LANs. And it tolerates a",
            "# named interface that is not there yet: a Wi-Fi access point appears",
            "# only once the radio is up, and under bind-interfaces its absence",
            "# stops dnsmasq starting at all, taking DHCP and DNS off the wired LAN",
            "# too. One radio failing to come up must not darken the whole box.",
            "except-interface=lo",
            "bind-dynamic",
        ]
        for interface in self._lans:
            lines.append(f"interface={interface.device_name}")
        lines.append("")
        return lines

    def _render_upstream(self) -> list[str]:
        """Where queries go, which follows the master proxy switch.

        With the proxy on, the only upstream is the xray DNS inbound, so a name
        is resolved at the exit node and no plaintext query ever leaves by an
        uplink. With it off, sending queries through xray anyway would be both
        pointless and fragile — the answer would come from the exit node for
        traffic that is not going there, and the LAN would lose DNS entirely
        whenever xray was stopped. So they go straight to the direct resolver,
        and the box works as a plain router with xray not running at all.
        """
        if self._routing.get("is_proxy_enabled", True):
            return [
                "# The only upstream is the xray DNS inbound, so queries resolve at",
                "# the exit node instead of leaking to whatever DNS the WAN handed us.",
                "no-resolv",
                f"server={XRAY_DNS_LISTEN}#{XRAY_DNS_PORT}",
                "",
            ]
        direct = self._routing.get("direct_dns") or {}
        address = direct.get("address", "223.5.5.5")
        port = direct.get("port", 53)
        return [
            "# The proxy is switched off, so queries go straight to the direct",
            "# resolver. Routing them through xray would resolve them at an exit",
            "# node the traffic is not using, and would take DNS off the LAN",
            "# entirely whenever xray was stopped.",
            "no-resolv",
            f"server={address}#{port}",
            "",
        ]

    def _render_dhcp(self) -> list[str]:
        pools = [
            interface
            for interface in self._lans
            if interface.lan.is_dhcp_enabled and interface.lan.dhcp_range_start
        ]
        if not pools:
            return ["# No LAN hands out leases; dnsmasq serves DNS only.", ""]
        lines = [
            "# DHCP: clients get this box as both gateway and resolver. dnsmasq tags",
            "# every request with the interface it arrived on, which is what keeps a",
            "# client on one network from being handed the gateway's address on",
            "# another.",
        ]
        for interface in pools:
            lines += self._render_pool(interface)
        lines += ["dhcp-authoritative", ""]
        return lines

    def _render_pool(self, interface: RouterInterface) -> list[str]:
        lan = interface.lan
        device = interface.device_name
        return [
            f"dhcp-range={lan.dhcp_range_start},{lan.dhcp_range_end},"
            f"{lan.dhcp_lease_time}",
            f"dhcp-option=tag:{device},option:router,{lan.address}",
            f"dhcp-option=tag:{device},option:dns-server,{lan.address}",
        ]
