"""Rendering the hostapd configuration for a Wi-Fi interface serving a network.

The gateway runs its own access point rather than asking NetworkManager for one.
NetworkManager's AP mode comes with ``ipv4.method=shared``, which is not a
detail that can be turned off — on a netplan-backed system the method is derived
from the mode and every attempt to set it back is normalised away. Shared means
NetworkManager starts a second dnsmasq of its own on the access point's address,
and that dnsmasq answers clients from the system resolver. Two things break at
once: it holds port 53, so the gateway's own dnsmasq cannot start and the wired
LAN loses DHCP and DNS with it; and every name a Wi-Fi client looks up would be
resolved outside the proxy, which is the one thing this box exists to prevent.

So the radio is ours: hostapd runs the access point, the gateway's dnsmasq
serves it, and nftables carries the traffic, exactly as for a wired LAN.

Pure: this module turns settings into configuration text. Starting hostapd is
:mod:`neutrino_hub.modules.router.wifi`.
"""

from neutrino_hub.modules.router.interfaces import RouterInterface

# Channels to publish on when nothing else is asked for. Fixed rather than
# automatic: hostapd's channel selection needs driver survey support that not
# every card has, and failing to start is worse than an unlucky channel.
DEFAULT_CHANNEL_2GHZ = 6
DEFAULT_CHANNEL_5GHZ = 36

BAND_2GHZ = "bg"
BAND_5GHZ = "a"


class RouterHostapdRenderer:
    """Builds one interface's hostapd configuration."""

    def __init__(self, *, interface: RouterInterface, country_code: str | None = None):
        """
        Args:
            interface: The interface, which must hold the LAN role and carry
                the access-point settings under ``wifi``.
            country_code: Two-letter regulatory domain, when the system knows
                one. Omitted rather than guessed: a wrong domain can put the
                radio on channels it may not legally use.
        """
        self._interface = interface
        self._country_code = country_code

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready for ``hostapd``.
        """
        wifi = self._interface.wifi
        is_5ghz = wifi.ap_band == BAND_5GHZ
        lines = [
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
            f"interface={self._interface.name}",
            "driver=nl80211",
            "",
            f"ssid={wifi.ap_ssid}",
            f"hw_mode={'a' if is_5ghz else 'g'}",
            f"channel={DEFAULT_CHANNEL_5GHZ if is_5ghz else DEFAULT_CHANNEL_2GHZ}",
        ]
        if self._country_code:
            lines += [
                f"country_code={self._country_code}",
                "ieee80211d=1",
            ]
        lines += [
            "",
            "# 802.11n and WMM: without WMM the link is capped at 802.11g rates,",
            "# which is a surprising thing for a new access point to do.",
            "ieee80211n=1",
            "wmm_enabled=1",
            "",
            "# WPA2 only. There is no open option: an access point with no",
            "# passphrase is an open route into the LAN.",
            "auth_algs=1",
            "wpa=2",
            "wpa_key_mgmt=WPA-PSK",
            "rsn_pairwise=CCMP",
            f"wpa_passphrase={wifi.ap_passphrase}",
            "",
            "ignore_broadcast_ssid=0",
            "",
        ]
        return "\n".join(lines)

    def render_address(self) -> str:
        """Render the environment file the unit reads the address from.

        hostapd does not do addressing, and nothing else on this interface will
        either — NetworkManager has been told to leave it alone. The unit sets
        the address itself before starting, from here, so the access point
        comes back after a reboot without the panel being involved.

        Returns:
            An environment file assigning ``AP_ADDRESS``.
        """
        return (
            "# Generated by neutrino. Do not edit; change config/ instead.\n"
            f"AP_ADDRESS={self._interface.lan.cidr}\n"
        )
