"""Rendering the nftables ruleset: the firewall, and the proxy's diversion.

Pure: this module turns ``config/`` data into ruleset text and never touches the
system. Loading the result is :mod:`neutrino_hub.modules.router.routes`. The
chains that divert into the proxy are the proxy's own, taken from the
edition table; a tree without the proxy renders the firewall alone.
"""

import ipaddress

from neutrino_hub import edition
from neutrino_hub.modules.router.constants import (
    ROUTER_NFT_FAMILY,
    ROUTER_NFT_TABLE,
    ROUTER_RESERVED_NETWORKS,
)
from neutrino_hub.modules.router.interfaces import RouterNetworkConfig


class RouterNftRenderer:
    """Builds the whole ``inet neutrino`` table from the router config.

    The table carries five chains: ``prerouting`` diverts LAN traffic into the
    TPROXY socket, ``output`` optionally does the same for the gateway's own
    traffic, ``forward`` and ``input`` are the firewall, and ``postrouting``
    masquerades whatever leaves through a WAN. The first two are the proxy's,
    and a tree without it renders the other three.

    Which interfaces those chains name comes from the roles in the network
    config, so a box with two LANs or two uplinks renders the same rules over
    a larger set rather than needing different ones. ``input`` is the one that
    reads something else: what answers where is a firewall question, not a
    role, and it is asked once per interface.
    """

    def __init__(
        self,
        *,
        network: RouterNetworkConfig,
        routing: dict,
        xray_uid: int,
        overlay_devices: dict | None = None,
        engine_cgroups: list | None = None,
        direct_port: "int | None" = None,
    ):
        """
        Args:
            network: The parsed router configuration.
            routing: The proxy's routing options, handed to its chains;
                empty in a tree without the proxy.
            xray_uid: Numeric uid the xray service runs as, handed to the
                proxy's chains; 0 in a tree without the proxy.
            overlay_devices: Provider to the kernel devices its overlay rides
                on, found at run time; a provider left out rides on its
                engine's own device. None keeps what ``network`` carries.
            engine_cgroups: The overlay engines' cgroups present now, each a
                path under the cgroup root such as
                ``system.slice/neutrino_hub_netbird.service``. Their packets
                leave directly while the local proxy is on. Only paths that
                exist: nft refuses one that does not.
            direct_port: The agent port while Direct is on, which opens that
                port alone on every enabled interface not already answering;
                None while Direct is off.
        """
        if overlay_devices is not None:
            network = network.with_overlay_devices(overlay_devices)
        # Device names, not entry names: the untagged main of a split port is
        # config-side only, and the firewall must match the port itself.
        self._wans = network.wan_device_names
        self._lans = network.lan_device_names
        self._exposed = network.exposed_device_names
        self._exposed_overlays = network.exposed_overlay_device_names
        self._overlay_groups = [
            network.devices_of(overlay)
            for overlay in network.enabled_overlays
            if network.devices_of(overlay)
        ]
        self._answering = network.exposed_interfaces
        self._direct_port = direct_port
        self._direct_devices = (
            []
            if direct_port is None
            else [
                name
                for name in network.enabled_device_names
                if name not in self._answering
            ]
        )
        self._overlay_ports = network.exposed_overlay_peer_ports
        self._side_lans = _side_lan_subnets(network)
        self._is_inter_lan_allowed = network.is_inter_lan_allowed
        part = edition.hook("router_nft")
        self._proxy = (
            None
            if part is None
            else part(
                routing=routing,
                xray_uid=xray_uid,
                lan_devices=self._lans,
                exposed_overlay_devices=self._exposed_overlays,
                engine_cgroups=list(engine_cgroups or []),
            )
        )

    def render(self) -> str:
        """Render the complete ruleset.

        Returns:
            Text ready for ``nft -f -``, including the ``flush`` that makes
            reloading idempotent.
        """
        blocks = [
            "#!/usr/sbin/nft -f",
            "",
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
            "# Create-then-delete makes a reload idempotent whether or not the",
            "# table is already present.",
            f"table {ROUTER_NFT_FAMILY} {ROUTER_NFT_TABLE} {{}}",
            f"delete table {ROUTER_NFT_FAMILY} {ROUTER_NFT_TABLE}",
            "",
            f"table {ROUTER_NFT_FAMILY} {ROUTER_NFT_TABLE} {{",
            self._render_reserved_set(),
            self._render_prerouting(),
            self._render_output(),
            self._render_forward(),
            self._render_overlay_fence(),
            self._render_input(),
            self._render_postrouting(),
            "}",
            "",
        ]
        return "\n".join(block for block in blocks if block)

    def _render_reserved_set(self) -> str:
        elements = ", ".join(ROUTER_RESERVED_NETWORKS)
        return (
            "    set reserved_v4 {\n"
            "        type ipv4_addr\n"
            "        flags interval\n"
            f"        elements = {{ {elements} }}\n"
            "    }\n"
        )

    def _render_prerouting(self) -> str:
        if self._proxy is None:
            return ""
        return self._proxy.prerouting(_interface_set)

    def _render_output(self) -> str:
        if self._proxy is None:
            return ""
        return self._proxy.output()

    def _render_forward(self) -> str:
        if not self._lans and not self._wans:
            # Nothing here has a role that forwards, so this box is not a
            # router and the packets crossing it are somebody else's —
            # docker's, libvirt's, a container runtime nobody told us about.
            # A drop policy would cut those off silently.
            return (
                "    # No interface routes anything: whatever forwards here is\n"
                "    # not ours to police.\n"
                "    chain forward {\n"
                "        type filter hook forward priority filter; policy accept;\n"
                "    }\n"
            )
        lines = [
            "    chain forward {",
            "        type filter hook forward priority filter; policy drop;",
            "",
            "        ct state established,related accept",
            "        ct state invalid drop",
            "",
        ]
        if self._lans and self._wans:
            lines += [
                "        # The served networks reach the internet through the uplinks,",
                "        # whatever is not diverted included, so the box is a plain",
                "        # router rather than dark when nothing diverts.",
                f"        iifname {_interface_set(self._lans)} "
                f"oifname {_interface_set(self._wans)} accept",
            ]
        if self._side_lans:
            devices = [device for device, _ in self._side_lans]
            lines += [
                "",
                "        # A side-gateway network is also the way out: traffic",
                "        # hairpins back through the same wire to its real router,",
                "        # and every other network exits through it too.",
                f"        iifname {_interface_set(self._lans)} "
                f"oifname {_interface_set(devices)} accept",
            ]
        if len(self._lans) > 1:
            if self._is_inter_lan_allowed:
                lines += [
                    "",
                    "        # The served networks are one trust domain: a device",
                    "        # on the Wi-Fi and one on the wire can reach each other.",
                    f"        iifname {_interface_set(self._lans)} "
                    f"oifname {_interface_set(self._lans)} accept",
                ]
            else:
                lines += [
                    "",
                    "        # The served networks are fenced off from each other:",
                    "        # no rule here, so the drop policy holds between them.",
                ]
        if self._exposed_overlays:
            overlays = _interface_set(self._exposed_overlays)
            lines += [
                "",
                "        # An overlay reaches anything this box routes, the closed",
                "        # uplink's network included; which peers may is the",
                "        # overlay's own rule set's decision.",
                f"        iifname {overlays} accept",
            ]
            if self._lans:
                lines.append(
                    f"        iifname {_interface_set(self._lans)} "
                    f"oifname {overlays} accept"
                )
        lines += [
            "",
            "        # Containers on the podman bridge: without these the",
            "        # default-drop forward chain cuts every container off from",
            "        # the internet, silently.",
            '        iifname "podman0" accept',
            '        oifname "podman0" accept',
        ]
        lines.append("    }\n")
        return "\n".join(lines)

    def _render_overlay_fence(self) -> str:
        """The drops between two overlays, in a chain of their own.

        A chain one step ahead of ``forward``: an overlay daemon inserts an
        accept for its own device at the top of the forward chain, and a drop
        in an earlier chain holds whatever the later one accepts.

        Returns:
            The chain, one rule per ordered pair of running overlays; empty
            with fewer than two.
        """
        if len(self._overlay_groups) < 2:
            return ""
        lines = [
            "    # A peer of one overlay never reaches a peer of another",
            "    # through this box.",
            "    chain forward_overlays {",
            "        type filter hook forward priority filter - 1; policy accept;",
        ]
        for source in self._overlay_groups:
            for target in self._overlay_groups:
                if source is target:
                    continue
                lines.append(
                    f"        iifname {_interface_set(source)} "
                    f"oifname {_interface_set(target)} drop"
                )
        lines.append("    }\n")
        return "\n".join(lines)

    def _render_input(self) -> str:
        lines = [
            "    chain input {",
            "        type filter hook input priority filter; policy drop;",
            "",
            "        ct state established,related accept",
            "        ct state invalid drop",
            '        iifname "lo" accept',
        ]
        if self._proxy is not None:
            lines += self._proxy.input_lines()
        lines.append("")
        if self._answering:
            lines += [
                "        # Where this box answers. Every service here binds every",
                "        # address and settles its own port, so which wires reach",
                "        # them is the whole of the question, and it is one answer",
                "        # per interface, an overlay included.",
                f"        iifname {_interface_set(self._answering)} accept",
            ]
        if self._direct_devices:
            lines += [
                "        # Direct: the agent port alone on every other enabled",
                "        # interface; the rest of this box stays as exposed.",
                f"        iifname {_interface_set(self._direct_devices)} "
                f"tcp dport {self._direct_port} accept",
            ]
        lines.append("")
        closed_wans = [name for name in self._wans if name not in self._exposed]
        if closed_wans:
            external = _interface_set(closed_wans)
            lines += [
                "        # An uplink nobody exposed still has to be able to take a",
                "        # lease: this is the box being a client, not a service.",
                f"        iifname {external} udp dport 68 accept",
                f"        iifname {external} udp sport 67 accept",
            ]
        closed_lans = [name for name in self._lans if name not in self._exposed]
        if closed_lans:
            served = _interface_set(closed_lans)
            lines += [
                "        # A served network nobody exposed still gets its leases",
                "        # and its names: that is this box being its router, not a",
                "        # service somebody opted into.",
                f"        iifname {served} udp dport 67 accept",
                f"        iifname {served} udp dport 53 accept",
                f"        iifname {served} tcp dport 53 accept",
            ]
        lines += [
            "        icmp type { echo-request, destination-unreachable, "
            "time-exceeded, parameter-problem } accept",
            "        icmpv6 type { echo-request, nd-neighbor-solicit, "
            "nd-neighbor-advert, nd-router-advert } accept",
        ]
        if self._overlay_ports:
            ports = ", ".join(str(port) for port in self._overlay_ports)
            lines += [
                "        # Where each overlay's own peers knock, so they reach",
                "        # this box directly instead of through a relay.",
                f"        udp dport {{ {ports} }} accept",
            ]
        lines.append("    }\n")
        return "\n".join(lines)

    def _render_postrouting(self) -> str:
        lines = [
            "    chain postrouting {",
            "        type nat hook postrouting priority srcnat; policy accept;",
            "",
        ]
        if self._wans:
            lines.append(f"        oifname {_interface_set(self._wans)} masquerade")
        for device, subnet in self._side_lans:
            lines += [
                "        # Forwarded traffic leaving through the side gateway's",
                "        # router must carry the box's address, or the router",
                "        # replies past the box and conntrack never sees it.",
                "        # Delivery to the network's own hosts stays untouched.",
                f'        oifname "{device}" ip daddr != {subnet} masquerade',
            ]
        if not self._wans and not self._side_lans:
            lines.append("        # No uplink configured: nothing to masquerade.")
        lines.append("    }")
        return "\n".join(lines)


def _side_lan_subnets(network: RouterNetworkConfig) -> list[tuple[str, str]]:
    """The side-gateway networks as (device, subnet) pairs.

    Args:
        network: The parsed router configuration.

    Returns:
        One pair per LAN with an upstream router, the subnet normalised to its
        network address. An unparsable address is skipped rather than raised:
        the validation layers refuse it long before rendering.
    """
    pairs = []
    for interface in network.side_gateway_lans:
        try:
            subnet = ipaddress.ip_network(interface.lan.cidr, strict=False)
        except ValueError:
            continue
        pairs.append((interface.device_name, str(subnet)))
    return pairs


def _interface_set(names: list[str]) -> str:
    """Render interface names as an nft anonymous set.

    Args:
        names: One or more interface names.

    Returns:
        A quoted set literal such as ``{ "enp1s0", "wlp3s0" }``. Callers must
        not pass an empty list: nft rejects an empty set, and every rule that
        needs one is already skipped when there are no interfaces to name.
    """
    quoted = ", ".join(f'"{name}"' for name in names)
    return f"{{ {quoted} }}"
