"""Rendering the nftables ruleset that steers traffic into xray.

Pure: this module turns ``config/`` data into ruleset text and never touches the
system. Loading the result is :mod:`neutrino_hub.modules.router.routes`.
"""

import ipaddress

from neutrino_hub.modules.xray.constants import XRAY_TPROXY_LISTEN, XRAY_TPROXY_PORT

from neutrino_hub.modules.router.constants import (
    ROUTER_FWMARK_TPROXY,
    ROUTER_FWMARK_XRAY_EGRESS,
    ROUTER_NFT_FAMILY,
    ROUTER_NFT_TABLE,
    ROUTER_RESERVED_NETWORKS,
)
from neutrino_hub.modules.router.interfaces import RouterNetworkConfig


class RouterNftRenderer:
    """Builds the whole ``inet neutrino`` table from the router config.

    The table carries five chains: ``prerouting`` diverts LAN traffic into the
    TPROXY socket, ``output`` optionally does the same for the gateway's own
    traffic, ``forward`` and ``input`` are the firewall, and ``postrouting``
    masquerades whatever leaves through a WAN.

    Which interfaces those chains name comes from the roles in the network
    config, so a box with two LANs or two uplinks renders the same rules over
    a larger set rather than needing different ones. ``input`` is the one that
    reads something else: what answers where is a firewall question, not a
    role, and it is asked once per interface.
    """

    def __init__(
        self,
        *,
        network: RouterNetworkConfig,
        routing: dict,
        xray_uid: int,
    ):
        """
        Args:
            network: The parsed router configuration.
            routing: Parsed ``config/xray/routing.json``; only the LAN and
                local-proxy switches are read here.
            xray_uid: Numeric uid the xray service runs as. Traffic from this
                uid is never diverted, which is what stops the proxy from
                looping into itself.
        """
        # Device names, not entry names: the untagged main of a split port is
        # config-side only, and the firewall must match the port itself.
        self._wans = network.wan_device_names
        self._lans = network.lan_device_names
        self._exposed = network.exposed_device_names
        self._side_lans = _side_lan_subnets(network)
        self._is_inter_lan_allowed = network.is_inter_lan_allowed
        # Two independent scopes: what the box forwards, and the box itself.
        # Neither implies the other, so a server can proxy its own traffic
        # while forwarding nobody's.
        self._is_lan_proxy_enabled = routing.get("is_proxy_enabled", True)
        self._is_local_proxy_enabled = routing.get("is_local_proxy_enabled", False)
        self._xray_uid = xray_uid

    def render(self) -> str:
        """Render the complete ruleset.

        Returns:
            Text ready for ``nft -f -``, including the ``flush`` that makes
            reloading idempotent.
        """
        blocks = [
            "#!/usr/sbin/nft -f",
            "",
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
            "# Create-then-delete makes a reload idempotent whether or not the",
            "# table is already present.",
            f"table {ROUTER_NFT_FAMILY} {ROUTER_NFT_TABLE} {{}}",
            f"delete table {ROUTER_NFT_FAMILY} {ROUTER_NFT_TABLE}",
            "",
            f"table {ROUTER_NFT_FAMILY} {ROUTER_NFT_TABLE} {{",
            self._render_reserved_set(),
            self._render_prerouting(),
            self._render_output(),
            self._render_forward(),
            self._render_input(),
            self._render_postrouting(),
            "}",
            "",
        ]
        return "\n".join(block for block in blocks if block)

    def _render_reserved_set(self) -> str:
        elements = ", ".join(ROUTER_RESERVED_NETWORKS)
        return (
            "    set reserved_v4 {\n"
            "        type ipv4_addr\n"
            "        flags interval\n"
            f"        elements = {{ {elements} }}\n"
            "    }\n"
        )

    def _render_prerouting(self) -> str:
        target = f"{XRAY_TPROXY_LISTEN}:{XRAY_TPROXY_PORT}"
        lines = [
            "    chain prerouting {",
            "        type filter hook prerouting priority mangle; policy accept;",
            "",
            "        # Packets of an established transparent session: mark for local",
            "        # delivery and let the existing socket pick them up.",
            "        meta l4proto { tcp, udp } socket transparent 1 "
            f"meta mark set {hex(ROUTER_FWMARK_TPROXY)} accept",
            "",
        ]
        if self._is_local_proxy_enabled:
            lines += [
                "        # Gateway-originated traffic looped back by the output chain.",
                f'        iifname "lo" meta mark {hex(ROUTER_FWMARK_TPROXY)} '
                "meta l4proto { tcp, udp } "
                f"tproxy ip to {target} accept",
                "",
            ]
        if not self._is_lan_proxy_enabled:
            lines += [
                "        # LAN traffic is not sent to the proxy: it is forwarded",
                "        # and masqueraded like any router's.",
                "    }\n",
            ]
            return "\n".join(lines)
        if not self._lans:
            lines += [
                "        # No interface has the LAN role, so there is nothing to",
                "        # divert into the proxy.",
                "    }\n",
            ]
            return "\n".join(lines)
        lines += [
            "        # Everything below is LAN traffic being proxied.",
            f"        iifname != {_interface_set(self._lans)} return",
            "        ip daddr @reserved_v4 return",
            "        meta l4proto { tcp, udp } "
            f"tproxy ip to {target} meta mark set {hex(ROUTER_FWMARK_TPROXY)} accept",
            "    }\n",
        ]
        return "\n".join(lines)

    def _render_output(self) -> str:
        if not self._is_local_proxy_enabled:
            return (
                "    # Local proxy is off: the gateway's own traffic leaves directly.\n"
                "    chain output {\n"
                "        type route hook output priority mangle; policy accept;\n"
                "    }\n"
            )
        return "\n".join(
            [
                "    chain output {",
                "        type route hook output priority mangle; policy accept;",
                "",
                "        # Anti-loop: xray's own egress must never re-enter the proxy.",
                f"        meta skuid {self._xray_uid} return",
                f"        meta mark {hex(ROUTER_FWMARK_XRAY_EGRESS)} return",
                "        ip daddr @reserved_v4 return",
                "",
                "        # Mark the rest; the fwmark rule reroutes it to lo for TPROXY.",
                "        meta l4proto { tcp, udp } "
                f"meta mark set {hex(ROUTER_FWMARK_TPROXY)}",
                "    }\n",
            ]
        )

    def _render_forward(self) -> str:
        if not self._lans and not self._wans:
            # Nothing here has a role that forwards, so this box is not a
            # router and the packets crossing it are somebody else's —
            # docker's, libvirt's, a container runtime nobody told us about.
            # A drop policy would cut those off silently.
            return (
                "    # No interface routes anything: whatever forwards here is\n"
                "    # not ours to police.\n"
                "    chain forward {\n"
                "        type filter hook forward priority filter; policy accept;\n"
                "    }\n"
            )
        lines = [
            "    chain forward {",
            "        type filter hook forward priority filter; policy drop;",
            "",
            "        ct state established,related accept",
            "        ct state invalid drop",
            "",
        ]
        if self._lans and self._wans:
            lines += [
                "        # Traffic TPROXY did not divert (ICMP, and everything at all",
                "        # if xray is down) still reaches the internet, so the box",
                "        # degrades to a plain router rather than going dark.",
                f"        iifname {_interface_set(self._lans)} "
                f"oifname {_interface_set(self._wans)} accept",
            ]
        if self._side_lans:
            devices = [device for device, _ in self._side_lans]
            lines += [
                "",
                "        # A side-gateway network is also the way out: traffic",
                "        # hairpins back through the same wire to its real router,",
                "        # and every other network exits through it too.",
                f"        iifname {_interface_set(self._lans)} "
                f"oifname {_interface_set(devices)} accept",
            ]
        if len(self._lans) > 1:
            if self._is_inter_lan_allowed:
                lines += [
                    "",
                    "        # The served networks are one trust domain: a device",
                    "        # on the Wi-Fi and one on the wire can reach each other.",
                    f"        iifname {_interface_set(self._lans)} "
                    f"oifname {_interface_set(self._lans)} accept",
                ]
            else:
                lines += [
                    "",
                    "        # The served networks are fenced off from each other:",
                    "        # no rule here, so the drop policy holds between them.",
                ]
        lines += [
            "",
            "        # The overlay reaches the LAN and back: remote access in both",
            "        # directions. wt0 is netbird's WireGuard interface.",
            '        iifname "wt0" accept',
        ]
        if self._lans:
            lines.append(
                f"        iifname {_interface_set(self._lans)} " 'oifname "wt0" accept'
            )
        lines += [
            "",
            "        # Containers on the podman bridge: without these the",
            "        # default-drop forward chain cuts every container off from",
            "        # the internet, silently.",
            '        iifname "podman0" accept',
            '        oifname "podman0" accept',
        ]
        lines.append("    }\n")
        return "\n".join(lines)

    def _render_input(self) -> str:
        lines = [
            "    chain input {",
            "        type filter hook input priority filter; policy drop;",
            "",
            "        ct state established,related accept",
            "        ct state invalid drop",
            '        iifname "lo" accept',
            "",
        ]
        if self._exposed:
            lines += [
                "        # Where this box answers. Every service here binds every",
                "        # address and settles its own port, so which wires reach",
                "        # them is the whole of the question, and it is one answer",
                "        # per interface.",
                f"        iifname {_interface_set(self._exposed)} accept",
            ]
        lines += [
            "        # The overlay always answers: it is how a box nobody exposed",
            "        # is reached at all.",
            '        iifname "wt0" accept',
            "",
        ]
        closed_wans = [name for name in self._wans if name not in self._exposed]
        if closed_wans:
            external = _interface_set(closed_wans)
            lines += [
                "        # An uplink nobody exposed still has to be able to take a",
                "        # lease: this is the box being a client, not a service.",
                f"        iifname {external} udp dport 68 accept",
                f"        iifname {external} udp sport 67 accept",
            ]
        lines += [
            "        icmp type { echo-request, destination-unreachable, "
            "time-exceeded, parameter-problem } accept",
            "        icmpv6 type { echo-request, nd-neighbor-solicit, "
            "nd-neighbor-advert, nd-router-advert } accept",
            # NetBird's WireGuard port, so peers can reach this box directly.
            "        udp dport 51820 accept",
            "    }\n",
        ]
        return "\n".join(lines)

    def _render_postrouting(self) -> str:
        lines = [
            "    chain postrouting {",
            "        type nat hook postrouting priority srcnat; policy accept;",
            "",
        ]
        if self._wans:
            lines.append(f"        oifname {_interface_set(self._wans)} masquerade")
        for device, subnet in self._side_lans:
            lines += [
                "        # Forwarded traffic leaving through the side gateway's",
                "        # router must carry the box's address, or the router",
                "        # replies past the box and conntrack never sees it.",
                "        # Delivery to the network's own hosts stays untouched.",
                f'        oifname "{device}" ip daddr != {subnet} masquerade',
            ]
        if not self._wans and not self._side_lans:
            lines.append("        # No uplink configured: nothing to masquerade.")
        lines.append("    }")
        return "\n".join(lines)


def _side_lan_subnets(network: RouterNetworkConfig) -> list[tuple[str, str]]:
    """The side-gateway networks as (device, subnet) pairs.

    Args:
        network: The parsed router configuration.

    Returns:
        One pair per LAN with an upstream router, the subnet normalised to its
        network address. An unparsable address is skipped rather than raised:
        the validation layers refuse it long before rendering.
    """
    pairs = []
    for interface in network.side_gateway_lans:
        try:
            subnet = ipaddress.ip_network(interface.lan.cidr, strict=False)
        except ValueError:
            continue
        pairs.append((interface.device_name, str(subnet)))
    return pairs


def _interface_set(names: list[str]) -> str:
    """Render interface names as an nft anonymous set.

    Args:
        names: One or more interface names.

    Returns:
        A quoted set literal such as ``{ "enp1s0", "wlp3s0" }``. Callers must
        not pass an empty list: nft rejects an empty set, and every rule that
        needs one is already skipped when there are no interfaces to name.
    """
    quoted = ", ".join(f'"{name}"' for name in names)
    return f"{{ {quoted} }}"
