"""What the box itself resolves names with.

A box in router mode resolves where its own devices do: at the dnsmasq on its
served network, which forwards through the proxy or to the direct resolver as
the routing configuration says. Without this the gateway comes up with an
address, a route, and nothing to ask a name of — it cannot fetch its own
geodata, install a module from a vendor, or run apt.

It has to be written rather than inherited. The lease client's `resolv.conf`
hook is off, because a hook that writes the upstream network's servers into
this file is a second opinion about the one thing the whole box exists to
route; and on a machine whose resolver was `systemd-resolved`, that daemon is
stopped in router mode and the stub it answered on is gone.

Only in router mode. A machine the hub does not address keeps whatever it was
resolving with, like everything else about it.

An overlay client can hold the file itself: NetBird puts its own resolver in
front, keeps what it found in a file beside the original, and forwards every
other name to the servers named there. On such a machine that file is the one
written, so the box still resolves at its dnsmasq behind the overlay's
resolver, and the overlay's own names keep answering.

Not pure: writes a file outside the hub's own roots.
"""

import os
from pathlib import Path

from neutrino_hub.utils.subprocess_run import run

# --- config ---
RESOLVER_PATH = Path("/etc/resolv.conf")
# Where systemd-resolved answers, and what a distribution symlinks the file
# above at when it is the resolver. Pointing back at it is how the machine's
# own arrangement is restored without anything having been backed up.
RESOLVER_RESOLVED_STUB = Path("/run/systemd/resolve/stub-resolv.conf")
RESOLVER_RESOLVED_UNIT = "systemd-resolved.service"

RESOLVER_HEADER = "# Written by neutrino. Change config/ rather than this file.\n"
# How NetBird marks a resolver file of its own, and where it keeps the one it
# replaced: that copy names the servers it forwards to.
RESOLVER_NETBIRD_HEADER = "# Generated by NetBird"
RESOLVER_NETBIRD_ORIGINAL = Path("/etc/resolv.conf.original.netbird")


def point_at(address: str) -> bool:
    """Have the box resolve at one address.

    Args:
        address: Where its dnsmasq listens, which is its own address on the
            network it serves.

    Returns:
        True when the file had to be written.
    """
    wanted = f"{RESOLVER_HEADER}nameserver {address}\n"
    target = _target()
    if _current(target) == wanted:
        return False
    _replace(target, wanted)
    return True


def hand_back() -> bool:
    """Give name resolution back to whatever the machine had.

    A symlink to `systemd-resolved`'s stub when that is installed, which is
    what every distribution using it ships. Otherwise the file is left as it
    is: something else on this machine writes it, and guessing at servers
    would be worse than leaving what is there.

    Returns:
        True when the file was changed.
    """
    target = _target()
    if not _is_written_here(target):
        return False
    is_resolved = run(
        ["systemctl", "is-enabled", "--quiet", RESOLVER_RESOLVED_UNIT],
        is_checked=False,
    ).is_success
    if not is_resolved:
        return False
    target.unlink(missing_ok=True)
    target.symlink_to(RESOLVER_RESOLVED_STUB)
    return True


def _target() -> Path:
    """The file this box's own resolver is written to.

    Returns:
        NetBird's copy of the original while NetBird holds the file, so
        the resolver written is the one it forwards to; the file itself
        otherwise.
    """
    if _current(RESOLVER_PATH).startswith(RESOLVER_NETBIRD_HEADER):
        return RESOLVER_NETBIRD_ORIGINAL
    return RESOLVER_PATH


def _is_written_here(path: Path) -> bool:
    """Whether a file is one this module wrote.

    Args:
        path: The file.

    Returns:
        True when it carries our header, so nothing somebody else arranged is
        ever replaced by handing back.
    """
    return _current(path).startswith(RESOLVER_HEADER)


def _current(path: Path) -> str:
    """What a file says now, or an empty string when it cannot be read."""
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _replace(path: Path, text: str) -> None:
    """Write a file, whatever is in its place.

    A symlink is removed rather than written through: on a machine using
    `systemd-resolved` this path is a link into `/run`, and writing through it
    would put our nameserver in a file that daemon rewrites — or, once it is
    stopped, in a file under a directory that no longer exists.

    Args:
        path: The file.
        text: The whole file.
    """
    temporary = path.with_suffix(".neutrino")
    temporary.write_text(text, encoding="utf-8")
    os.chmod(temporary, 0o644)
    path.unlink(missing_ok=True)
    os.replace(temporary, path)
