"""What the box itself resolves names with.

A box in router mode resolves where its own devices do: at the dnsmasq on its
served network, which forwards through the proxy or to the direct resolver as
the routing configuration says. Without this the gateway comes up with an
address, a route, and nothing to ask a name of — it cannot fetch its own
geodata, install a module from a vendor, or run apt.

It has to be written rather than inherited. The lease client's `resolv.conf`
hook is off, because a hook that writes the upstream network's servers into
this file is a second opinion about the one thing the whole box exists to
route; and on a machine whose resolver was `systemd-resolved`, that daemon is
stopped in router mode and the stub it answered on is gone.

Only in router mode. A machine the hub does not address keeps whatever it was
resolving with, like everything else about it.

NetBird's DNS management is kept off on a hub, so the file is the hub's own.
A daemon that wrote the file before it was told puts its own resolver in
front, keeps what it found in a file beside the original, and forwards every
other name to the servers named there; on such a machine that copy is the one
written, until the next network apply turns the management off.

The file found before the first write is kept under the state root and put
back on hand-back.

Not pure: writes a file outside the hub's own roots.
"""

import os
import shutil
from pathlib import Path

from neutrino_hub.modules.router.constants import (
    ROUTER_RESOLVER_ORIGINAL_PATH,
    ROUTER_RESOLVER_TO_FALLBACK,
    ROUTER_RESOLVER_TO_ORIGINAL,
    ROUTER_RESOLVER_TO_RESOLVED,
)
from neutrino_hub.utils.subprocess_run import run

# --- config ---
RESOLVER_PATH = Path("/etc/resolv.conf")
# Where systemd-resolved answers, and what a distribution symlinks the file
# above at when it is the resolver. Pointing back at it is how the machine's
# own arrangement is restored without anything having been backed up.
RESOLVER_RESOLVED_STUB = Path("/run/systemd/resolve/stub-resolv.conf")
RESOLVER_RESOLVED_UNIT = "systemd-resolved.service"

RESOLVER_HEADER = "# Written by neutrino. Change config/ rather than this file.\n"
# How NetBird marks a resolver file of its own, and where it keeps the one it
# replaced: that copy names the servers it forwards to.
RESOLVER_NETBIRD_HEADER = "# Generated by NetBird"
RESOLVER_NETBIRD_ORIGINAL = Path("/etc/resolv.conf.original.netbird")


def point_at(address: str) -> bool:
    """Have the box resolve at one address.

    Args:
        address: Where its dnsmasq listens, which is its own address on the
            network it serves.

    Returns:
        True when the file had to be written.
    """
    wanted = f"{RESOLVER_HEADER}nameserver {address}\n"
    target = _target()
    if _current(target) == wanted:
        return False
    _keep_original(target)
    _replace(target, wanted)
    return True


def hand_back(*, fallback_address: str = "") -> str:
    """Give name resolution back to whatever the machine had.

    In order: a symlink to `systemd-resolved`'s stub when that unit is
    enabled; the file kept before the first write; a file naming the
    fallback address.

    Args:
        fallback_address: The direct resolver, written when neither of the
            first two applies; empty leaves the file as it is.

    Returns:
        :data:`ROUTER_RESOLVER_TO_RESOLVED`,
        :data:`ROUTER_RESOLVER_TO_ORIGINAL` or
        :data:`ROUTER_RESOLVER_TO_FALLBACK` for what was written, or an
        empty string when the file is not ours or nothing was written.

    Raises:
        OSError: If the file cannot be written.
    """
    target = _target()
    if not _is_written_here(target):
        return ""
    is_resolved = run(
        ["systemctl", "is-enabled", "--quiet", RESOLVER_RESOLVED_UNIT],
        is_checked=False,
    ).is_success
    original = ROUTER_RESOLVER_ORIGINAL_PATH
    if is_resolved:
        target.unlink(missing_ok=True)
        target.symlink_to(RESOLVER_RESOLVED_STUB)
        original.unlink(missing_ok=True)
        return ROUTER_RESOLVER_TO_RESOLVED
    if original.is_symlink() or original.exists():
        _restore(original, target)
        return ROUTER_RESOLVER_TO_ORIGINAL
    if fallback_address:
        _replace(target, f"{RESOLVER_HEADER}nameserver {fallback_address}\n")
        return ROUTER_RESOLVER_TO_FALLBACK
    return ""


def _keep_original(target: Path) -> None:
    """Copy the file about to be replaced, the first time only.

    A symlink is kept as a symlink to the same place.

    Args:
        target: The file about to be written.
    """
    original = ROUTER_RESOLVER_ORIGINAL_PATH
    if original.is_symlink() or original.exists():
        return
    if _is_written_here(target):
        return
    if not (target.is_symlink() or target.exists()):
        return
    original.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink():
        os.symlink(os.readlink(target), original)
    else:
        shutil.copy2(target, original)


def _restore(original: Path, target: Path) -> None:
    """Put the kept file back in place and delete the copy.

    Args:
        original: The copy under the state root.
        target: The file it was taken from.
    """
    temporary = target.with_suffix(".neutrino")
    temporary.unlink(missing_ok=True)
    if original.is_symlink():
        os.symlink(os.readlink(original), temporary)
    else:
        shutil.copy2(original, temporary)
    os.replace(temporary, target)
    original.unlink()


def _target() -> Path:
    """The file this box's own resolver is written to.

    Returns:
        NetBird's copy of the original while NetBird holds the file, so
        the resolver written is the one it forwards to; the file itself
        otherwise.
    """
    if _current(RESOLVER_PATH).startswith(RESOLVER_NETBIRD_HEADER):
        return RESOLVER_NETBIRD_ORIGINAL
    return RESOLVER_PATH


def _is_written_here(path: Path) -> bool:
    """Whether a file is one this module wrote.

    Args:
        path: The file.

    Returns:
        True when it carries our header, so nothing somebody else arranged is
        ever replaced by handing back.
    """
    return _current(path).startswith(RESOLVER_HEADER)


def _current(path: Path) -> str:
    """What a file says now, or an empty string when it cannot be read."""
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _replace(path: Path, text: str) -> None:
    """Write a file, whatever is in its place.

    A symlink is removed rather than written through: on a machine using
    `systemd-resolved` this path is a link into `/run`, and writing through it
    would put our nameserver in a file that daemon rewrites — or, once it is
    stopped, in a file under a directory that no longer exists.

    Args:
        path: The file.
        text: The whole file.
    """
    temporary = path.with_suffix(".neutrino")
    temporary.write_text(text, encoding="utf-8")
    os.chmod(temporary, 0o644)
    path.unlink(missing_ok=True)
    os.replace(temporary, path)
