"""Rendering the `wpa_supplicant` configuration a radio joins networks with.

One file per radio, holding every network the box knows in the order it should
prefer them. `wpa_supplicant` picks among them itself: it scans, finds which
are in range, and associates with the highest priority of those — which is why
there is nothing here that decides between networks, and nothing that has to
be re-rendered when the box is carried somewhere else.

Pure: this module turns configuration into text. Starting the supplicant is
:mod:`neutrino_hub.modules.router.supplicant`.
"""

import string

from neutrino_hub.modules.router.connections import (
    RouterConnection,
    RouterConnectionSet,
)
from neutrino_hub.modules.router.constants import (
    ROUTER_KEY_MGMT_NONE,
    ROUTER_KEY_MGMT_SAE,
    ROUTER_PSK_HEX_LENGTH,
    ROUTER_SUPPLICANT_CONTROL_DIR,
)

# The supplicant runs as root under its unit, so the control socket is the
# hub's own to talk to and nobody else's to find.
SUPPLICANT_CONTROL_GROUP = "root"

# Protected Management Frames, which WPA3 requires and WPA2 may offer. 2 is
# required, 1 is optional: an SAE network cannot associate without it, and a
# PSK network that has it available is better off using it.
SUPPLICANT_PMF_REQUIRED = 2
SUPPLICANT_PMF_OPTIONAL = 1


class RouterSupplicantRenderer:
    """Builds one radio's supplicant configuration."""

    def __init__(
        self, *, connections: RouterConnectionSet, country_code: str | None = None
    ):
        """
        Args:
            connections: Every network the box knows. Only those it can
                actually associate with are written.
            country_code: Two-letter regulatory domain, when the system knows
                one. Omitted rather than guessed: a wrong domain hides the
                channels a network may be broadcasting on.
        """
        self._connections = connections
        self._country_code = country_code

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready for ``wpa_supplicant -c``. A radio with no networks to
            join still gets a valid file: the supplicant runs, finds nothing,
            and is there the moment somebody picks a network in the panel.
        """
        lines = [
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
            f"ctrl_interface=DIR={ROUTER_SUPPLICANT_CONTROL_DIR} "
            f"GROUP={SUPPLICANT_CONTROL_GROUP}",
            # The supplicant must never write back over this file. It is
            # rendered from `config/`, and a supplicant that saved into it
            # would put a network in a generated file where the next render
            # would silently drop it again.
            "update_config=0",
            "ap_scan=1",
        ]
        if self._country_code:
            lines.append(f"country={self._country_code}")
        for connection in self._connections.joinable():
            lines += ["", *_network_block(connection)]
        lines.append("")
        return "\n".join(lines)


def _network_block(connection: RouterConnection) -> list[str]:
    """One `network={}` block.

    Args:
        connection: The network to write.

    Returns:
        The block's lines.
    """
    lines = ["network={", f"    ssid={_quoted(connection.ssid)}"]
    if connection.is_hidden:
        # A network that does not broadcast its name is only found by asking
        # for it by name, which is what this turns on.
        lines.append("    scan_ssid=1")
    if connection.is_open:
        lines.append(f"    key_mgmt={ROUTER_KEY_MGMT_NONE}")
    elif connection.key_mgmt == ROUTER_KEY_MGMT_SAE:
        lines += [
            f"    key_mgmt={ROUTER_KEY_MGMT_SAE}",
            f"    ieee80211w={SUPPLICANT_PMF_REQUIRED}",
            # SAE derives its key from the passphrase during the handshake, so
            # this is the one case where a pre-derived key is no use.
            f"    sae_password={_quoted(connection.psk)}",
        ]
    else:
        lines += [
            f"    key_mgmt={connection.key_mgmt}",
            f"    ieee80211w={SUPPLICANT_PMF_OPTIONAL}",
            f"    psk={_psk(connection.psk)}",
        ]
    if connection.priority:
        lines.append(f"    priority={connection.priority}")
    lines.append("}")
    return lines


def _psk(secret: str) -> str:
    """A key in the form the supplicant expects it.

    Args:
        secret: What was stored — either the passphrase or the key derived
            from it.

    Returns:
        The derived key bare, and a passphrase quoted. The supplicant tells
        them apart the same way: 64 hexadecimal characters is a key, anything
        else is something to derive one from.
    """
    if len(secret) == ROUTER_PSK_HEX_LENGTH and _is_hexadecimal(secret):
        return secret
    return _quoted(secret)


def _is_hexadecimal(value: str) -> bool:
    """Whether every character is a hexadecimal digit.

    Character by character rather than through ``int``, which also accepts a
    ``0x`` prefix and underscores — so a passphrase of exactly the right
    length made of those would be written as a derived key and never work.

    Args:
        value: The text.

    Returns:
        True when it is only hexadecimal digits.
    """
    return all(character in string.hexdigits for character in value)


def _quoted(value: str) -> str:
    """A string value, escaped the way the supplicant's parser reads it.

    Args:
        value: The text.

    Returns:
        It in double quotes, with backslashes and quotes escaped — an SSID
        may contain either, and one that ends a string early would put the
        rest of the name into the file as configuration.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
