from pathlib import Path

GITEA_VERSION = "1.24.3"
GITEA_BINARY_PATH = Path("/usr/local/bin/gitea")
GITEA_USER = "git"
GITEA_DIR = Path("/var/lib/gitea")

GITEA_DEFAULT_PORT = 3000

# The whole of app.ini is generated, symlinked from /etc/gitea the way
# smb.conf and dnsmasq are. It holds secrets, so unlike those two the
# generated file is group-readable by the git user and nobody else.
GITEA_CONF_LINK_PATH = Path("/etc/gitea/app.ini")
GITEA_GENERATED_NAME = "gitea_app.ini"

# Machine secrets app.ini needs (session signing, internal auth, JWTs).
# Generated by `gitea generate secret` on first apply and kept in
# config/gitea/secrets.json, gitignored: losing them on a rebuild only
# invalidates sessions and tokens, never repositories.
GITEA_SECRET_NAMES = ("SECRET_KEY", "INTERNAL_TOKEN", "JWT_SECRET", "LFS_JWT_SECRET")

# Gitea is downloaded as a prebuilt binary, so only the architectures the
# vendor publishes are supported — and the download must pick the right one.
GITEA_SUPPORTED_ARCHITECTURES = ("amd64", "arm64", "arm-6")
