"""Rendering the whole of ``app.ini`` from the git server's configuration.

The whole file, with ``INSTALL_LOCK`` already set: Gitea's browser install
wizard exists to ask questions this gateway already knows the answers to, and
a box that boots into a "please configure me" page is not plug-and-play.

Pure: text in, text out. The secrets are handed in — generating them takes
the gitea binary, which is an effect and lives in :mod:`neutrino_hub.modules.gitea.ops`.
"""

from neutrino_hub.modules.gitea.config import GiteaConfig
from neutrino_hub.modules.gitea.constants import GITEA_DIR, GITEA_USER


class GiteaConfigRenderer:
    """Builds ``app.ini`` from the parsed configuration."""

    def __init__(self, *, config: GiteaConfig, lan_address: str, secrets: dict):
        """
        Args:
            config: The parsed configuration.
            lan_address: The primary LAN address, used to derive the root URL
                and SSH domain when no override is set.
            secrets: The machine secrets by name — every
                :data:`neutrino_hub.modules.gitea.constants.GITEA_SECRET_NAMES` entry.
        """
        self._config = config
        self._lan_address = lan_address
        self._secrets = secrets

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready to write as ``app.ini``.
        """
        config = self._config
        root_url = (
            config.root_url or f"http://{self._lan_address}:{config.listen_port}/"
        )
        # What clone addresses and links say, which need not be where it binds.
        domain = root_url.split("//", 1)[1].split("/", 1)[0].split(":", 1)[0]
        registration = "false" if config.is_registration_enabled else "true"
        return f"""; Generated by neutrino. Do not edit; change config/ instead.

APP_NAME = Neutrino Gitea
RUN_USER = {GITEA_USER}
RUN_MODE = prod
WORK_PATH = {GITEA_DIR}

[server]
PROTOCOL = http
; Binds everywhere and lets the firewall decide who reaches it: the input
; chain already drops the WAN, and an overlay interface added later is served
; without a rebind.
HTTP_ADDR = 0.0.0.0
HTTP_PORT = {config.listen_port}
DOMAIN = {domain}
ROOT_URL = {root_url}
; Clones over ssh go through the box's own sshd as the {GITEA_USER} user.
DISABLE_SSH = false
START_SSH_SERVER = false
SSH_DOMAIN = {domain}
SSH_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = {self._secrets["LFS_JWT_SECRET"]}
; Never fetch assets from a CDN: the box may sit behind a filter that would
; leave the UI half-loaded forever.
OFFLINE_MODE = true

[database]
DB_TYPE = sqlite3
PATH = {GITEA_DIR}/data/gitea.db

[repository]
ROOT = {GITEA_DIR}/data/gitea_repositories

[security]
; The browser install wizard is skipped: everything it would ask is here.
INSTALL_LOCK = true
SECRET_KEY = {self._secrets["SECRET_KEY"]}
INTERNAL_TOKEN = {self._secrets["INTERNAL_TOKEN"]}

[oauth2]
JWT_SECRET = {self._secrets["JWT_SECRET"]}

[service]
DISABLE_REGISTRATION = {registration}
REQUIRE_SIGNIN_VIEW = false

[session]
PROVIDER = file

[log]
MODE = file
ROOT_PATH = {GITEA_DIR}/log
LEVEL = Info

[actions]
; CI runners are a fleet feature; a personal gateway is not one.
ENABLED = false
"""
