"""Installing and removing the ZFS tools.

The kernel module ships with Ubuntu's kernel packages; what apt adds here is
the userland (``zpool``/``zfs``), the event daemon, and smartmontools for the
disk health column. Pools are never touched in either direction: they live on
their member disks, and removing the tools merely makes them unreachable
until the tools return.
"""

import shutil
from pathlib import Path
from typing import Callable

from neutrino_hub.system.provisioning import ProvisionResult, say
from neutrino_hub.utils.subprocess_run import run

from neutrino_hub.modules.zfs.constants import (
    ZFS_ARC_MAX_FRACTION,
    ZFS_ARC_MAX_PARAMETER,
    ZFS_MODPROBE_CONF,
)

# zfs-zed is spelled out: it is only a Recommends of zfsutils-linux, and the
# install runs without recommends.
ZFS_PACKAGES = ("zfsutils-linux", "zfs-zed", "smartmontools")

MEMINFO_PATH = Path("/proc/meminfo")


class ZfsProvisioner:
    """Installs the ZFS userland and takes it away again."""

    def provision(
        self, *, report: Callable[[str], None] | None = None
    ) -> ProvisionResult:
        """Install the tools and cap the ARC.

        Args:
            report: Sink for progress lines, if anyone is watching.

        Returns:
            What was done.

        Raises:
            CommandError: If apt fails.
        """
        if shutil.which("zpool"):
            self._cap_arc(report)
            return ProvisionResult(is_changed=False, message="already installed")
        say(report, "installing zfsutils-linux and smartmontools from Ubuntu")
        run(["apt-get", "update"], timeout_s=300, is_checked=False)
        run(
            ["apt-get", "install", "-y", "--no-install-recommends", *ZFS_PACKAGES],
            timeout_s=900,
        )
        self._cap_arc(report)
        return ProvisionResult(is_changed=True, message="installed")

    def deprovision(
        self,
        *,
        is_data_kept: bool = True,
        report: Callable[[str], None] | None = None,
    ) -> ProvisionResult:
        """Remove the tools. Pools stay on their disks, whatever was asked.

        ``is_data_kept`` is accepted for the uniform contract and ignored:
        destroying a pool is its own deliberate act in the ZFS page, never a
        side effect of uninstalling software.

        Args:
            is_data_kept: Ignored; the data is on the disks either way.
            report: Sink for progress lines, if anyone is watching.

        Returns:
            What was done.
        """
        if not shutil.which("zpool"):
            return ProvisionResult(is_changed=False, message="not installed")
        say(report, "removing the ZFS tools; pools stay intact on their disks")
        run(["apt-get", "remove", "-y", *ZFS_PACKAGES], timeout_s=600)
        ZFS_MODPROBE_CONF.unlink(missing_ok=True)
        return ProvisionResult(
            is_changed=True, message="removed; pools remain on their disks"
        )

    def _cap_arc(self, report: Callable[[str], None] | None) -> None:
        """Hold the ARC to a quarter of memory instead of its default half.

        The gateway runs services beside storage; a cache that takes half the
        machine forces them to fight for the rest. Written for the next boot
        and poked into the live module for this one.
        """
        arc_max = int(_total_memory_bytes() * ZFS_ARC_MAX_FRACTION)
        if arc_max <= 0:
            return
        wanted = (
            "# Generated by neutrino. Do not edit; the ZFS module owns it.\n"
            "# The ARC keeps to a quarter of memory: this box runs a gateway\n"
            "# first and a file server second.\n"
            f"options zfs zfs_arc_max={arc_max}\n"
        )
        if (
            not ZFS_MODPROBE_CONF.is_file()
            or ZFS_MODPROBE_CONF.read_text(encoding="utf-8") != wanted
        ):
            ZFS_MODPROBE_CONF.write_text(wanted, encoding="utf-8")
            say(report, f"capped the ARC at {arc_max // (1024 * 1024)} MiB")
        if ZFS_ARC_MAX_PARAMETER.is_file():
            try:
                ZFS_ARC_MAX_PARAMETER.write_text(str(arc_max), encoding="utf-8")
            except OSError:
                pass


def _total_memory_bytes() -> int:
    try:
        for line in MEMINFO_PATH.read_text(encoding="utf-8").splitlines():
            if line.startswith("MemTotal:"):
                return int(line.split()[1]) * 1024
    except (OSError, ValueError, IndexError):
        pass
    return 0
