"""Rendering the whole of ``smb.conf`` from the share configuration.

The whole file rather than an include: the stock Ubuntu file ships printer
shares and password-sync glue an appliance has no business serving, and a
partial include would leave those in place while claiming config/ is the whole
truth.

Pure: text in, text out. Writing, validating and reloading is
:mod:`neutrino_hub.modules.samba.ops`.
"""

import ipaddress

from neutrino_hub.modules.router.constants import ROUTER_MODE_SERVER
from neutrino_hub.modules.router.interfaces import RouterNetworkConfig
from neutrino_hub.modules.samba.constants import SAMBA_GROUP
from neutrino_hub.modules.samba.config import SambaConfig, SambaShare


def allowed_subnets(lan_cidrs: list, exposed_addresses: list) -> list:
    """The networks the shares answer, beside the firewall's own fence.

    Args:
        lan_cidrs: The LAN-role interfaces' cidrs, host form allowed.
        exposed_addresses: The exposed interfaces' live addresses with
            prefix (``a.b.c.d/nn``) — what carries the shares on a box
            whose addresses are its own, where no interface has a role.

    Returns:
        Deduplicated network addresses, order kept.
    """
    subnets = []
    for value in list(lan_cidrs) + list(exposed_addresses):
        if not value:
            continue
        try:
            network = str(ipaddress.ip_network(value, strict=False))
        except ValueError:
            continue
        if network not in subnets:
            subnets.append(network)
    return subnets


def share_subnets(
    *,
    network: RouterNetworkConfig,
    link_addresses: dict[str, str],
    device_addresses: dict[str, str],
) -> list[str]:
    """The networks the shares answer on, for one box as it is now.

    Rendered from two sources because the answer has two halves: which
    networks this box serves, which is configuration, and which addresses it
    holds, which is the kernel. Both call sites ask here rather than working
    it out themselves, so a fix to one is a fix to both.

    Args:
        network: The parsed router configuration.
        link_addresses: Interface name to live address with prefix, for the
            interfaces the hub assigns roles to.
        device_addresses: The same for every device on the box, which is
            where an overlay's address is found.

    Returns:
        Deduplicated network addresses, served networks first.
    """
    if network.mode == ROUTER_MODE_SERVER:
        # Nothing here has a role, so every wire the box holds an address on
        # is a wire its shares are meant to answer.
        reachable = [address for address in link_addresses.values() if address]
    else:
        reachable = [
            link_addresses.get(name, "") for name in network.exposed_device_names
        ]
    reachable += [
        device_addresses.get(name, "") for name in network.exposed_overlay_device_names
    ]
    return allowed_subnets(
        [interface.lan.cidr for interface in network.lan_interfaces], reachable
    )


class SambaConfigRenderer:
    """Builds ``smb.conf`` from the parsed configuration."""

    def __init__(self, *, config: SambaConfig, lan_subnets: list[str]):
        """
        Args:
            config: The parsed share configuration.
            lan_subnets: Networks allowed to reach the shares, for example
                ``["192.168.100.0/24"]``. The firewall already keeps the WAN
                out; this is the second fence, so a firewall mistake alone
                cannot expose the shares.
        """
        self._config = config
        self._lan_subnets = lan_subnets

    def render(self) -> str:
        """Render the configuration file.

        Returns:
            Text ready to write as ``smb.conf``.
        """
        lines = self._render_global()
        for share in self._config.shares:
            lines += self._render_share(share)
        return "\n".join(lines)

    def _render_global(self) -> list[str]:
        allowed = " ".join(self._lan_subnets + ["127.0.0.1"])
        return [
            "# Generated by neutrino. Do not edit; change config/ instead.",
            "",
            "[global]",
            "   server role = standalone server",
            "   server string = Neutrino Hub",
            "   disable netbios = yes",
            "   server min protocol = SMB2",
            "",
            "   # Accounts only, never guests: every connection is one of the",
            "   # configured users, so the sessions list below always has a name.",
            "   map to guest = never",
            "",
            f"   hosts allow = {allowed}",
            "   hosts deny = 0.0.0.0/0",
            "",
            "   logging = file",
            "   log file = /var/log/samba/log.%m",
            "   max log size = 1000",
            "",
            "   # No printers. The stock configuration exports them; a gateway",
            "   # has none and should not pretend otherwise.",
            "   load printers = no",
            "   printing = bsd",
            "   printcap name = /dev/null",
            "   disable spoolss = yes",
            "",
        ]

    def _render_share(self, share: SambaShare) -> list[str]:
        # A share limited to named users stays limited to them; one with no
        # list is open to the whole group, which is every configured user.
        if share.valid_users:
            valid = " ".join(share.valid_users)
        else:
            valid = f"@{SAMBA_GROUP}"
        lines = [
            f"[{share.name}]",
            f"   path = {share.path}",
            f"   valid users = {valid}",
            f"   read only = {'yes' if share.is_read_only else 'no'}",
        ]
        if share.comment:
            lines.append(f"   comment = {share.comment}")
        if not share.is_read_only:
            lines += [
                "   # Whatever one member creates stays writable to the others:",
                "   # the shared group is forced onto every new file, so two",
                "   # accounts editing one share never fight over ownership.",
                f"   force group = {SAMBA_GROUP}",
                "   create mask = 0664",
                "   directory mask = 2775",
            ]
        lines.append("")
        return lines
